[2024-11-18T21:05:10.855+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_recommender_dag_v3.preprocess_and_split manual__2024-11-18T21:05:01.049561+00:00 [queued]>
[2024-11-18T21:05:10.860+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_recommender_dag_v3.preprocess_and_split manual__2024-11-18T21:05:01.049561+00:00 [queued]>
[2024-11-18T21:05:10.860+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-11-18T21:05:10.867+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): preprocess_and_split> on 2024-11-18 21:05:01.049561+00:00
[2024-11-18T21:05:10.870+0000] {standard_task_runner.py:60} INFO - Started process 455 to run task
[2024-11-18T21:05:10.872+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_recommender_dag_v3', 'preprocess_and_split', 'manual__2024-11-18T21:05:01.049561+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/music_process.py', '--cfg-path', '/tmp/tmpl84_l1ma']
[2024-11-18T21:05:10.873+0000] {standard_task_runner.py:88} INFO - Job 124: Subtask preprocess_and_split
[2024-11-18T21:05:10.909+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_recommender_dag_v3.preprocess_and_split manual__2024-11-18T21:05:01.049561+00:00 [running]> on host e779a152538d
[2024-11-18T21:05:11.604+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_recommender_dag_v3' AIRFLOW_CTX_TASK_ID='preprocess_and_split' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T21:05:01.049561+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T21:05:01.049561+00:00'
[2024-11-18T21:05:11.606+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venv8y2d8x4i --system-site-packages --python=python
[2024-11-18T21:05:11.612+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T21:05:11.940+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 116ms
[2024-11-18T21:05:11.941+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venv8y2d8x4i, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T21:05:11.941+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T21:05:11.941+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-11-18T21:05:11.942+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T21:05:11.960+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv8y2d8x4i/bin/pip install -r /tmp/venv8y2d8x4i/requirements.txt
[2024-11-18T21:05:11.965+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T21:05:12.906+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venv8y2d8x4i/requirements.txt (line 1))
[2024-11-18T21:05:12.908+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T21:05:12.909+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venv8y2d8x4i/requirements.txt (line 2)) (2.0.3)
[2024-11-18T21:05:12.909+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn==1.3.2 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venv8y2d8x4i/requirements.txt (line 3)) (1.3.2)
[2024-11-18T21:05:13.316+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venv8y2d8x4i/requirements.txt (line 1))
[2024-11-18T21:05:13.318+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T21:05:13.319+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venv8y2d8x4i/requirements.txt (line 1)) (0.10.0)
[2024-11-18T21:05:13.343+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venv8y2d8x4i/requirements.txt (line 1))
[2024-11-18T21:05:13.344+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T21:05:13.396+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venv8y2d8x4i/requirements.txt (line 2)) (2.8.2)
[2024-11-18T21:05:13.396+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venv8y2d8x4i/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T21:05:13.397+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venv8y2d8x4i/requirements.txt (line 2)) (2023.4)
[2024-11-18T21:05:13.398+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy>=1.20.3 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venv8y2d8x4i/requirements.txt (line 2)) (1.24.4)
[2024-11-18T21:05:13.418+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy>=1.5.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venv8y2d8x4i/requirements.txt (line 3)) (1.10.1)
[2024-11-18T21:05:13.418+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venv8y2d8x4i/requirements.txt (line 3)) (1.4.2)
[2024-11-18T21:05:13.418+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venv8y2d8x4i/requirements.txt (line 3)) (3.5.0)
[2024-11-18T21:05:13.423+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venv8y2d8x4i/requirements.txt (line 1)) (1.26.18)
[2024-11-18T21:05:13.427+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas==2.0.3->-r /tmp/venv8y2d8x4i/requirements.txt (line 2)) (1.16.0)
[2024-11-18T21:05:13.662+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T21:05:13.664+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T21:05:13.675+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T21:05:15.431+0000] {process_utils.py:190} INFO - Installing collected packages: botocore, s3transfer, boto3
[2024-11-18T21:05:15.431+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T21:05:15.431+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T21:05:15.432+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv8y2d8x4i
[2024-11-18T21:05:15.432+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T21:05:15.837+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T21:05:15.838+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T21:05:15.838+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv8y2d8x4i
[2024-11-18T21:05:15.839+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T21:05:15.859+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T21:05:15.860+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T21:05:15.860+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv8y2d8x4i
[2024-11-18T21:05:15.860+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T21:05:15.891+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T21:05:15.891+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T21:05:15.891+0000] {process_utils.py:190} INFO - Successfully installed boto3-1.28.0 botocore-1.31.85 s3transfer-0.6.2
[2024-11-18T21:05:15.976+0000] {process_utils.py:190} INFO - 
[2024-11-18T21:05:15.977+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.3.1
[2024-11-18T21:05:15.977+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T21:05:16.096+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv8y2d8x4i/bin/python /tmp/venv-callkvp7nn_8/script.py /tmp/venv-callkvp7nn_8/script.in /tmp/venv-callkvp7nn_8/script.out /tmp/venv-callkvp7nn_8/string_args.txt /tmp/venv-callkvp7nn_8/termination.log
[2024-11-18T21:05:16.101+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T21:05:17.937+0000] {process_utils.py:190} INFO - Scaler saved to MinIO.
[2024-11-18T21:05:18.144+0000] {python.py:201} INFO - Done. Returned value was: Data preprocessed and saved.
[2024-11-18T21:05:18.159+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=spotify_recommender_dag_v3, task_id=preprocess_and_split, execution_date=20241118T210501, start_date=20241118T210510, end_date=20241118T210518
[2024-11-18T21:05:18.208+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-11-18T21:05:18.217+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
