[2024-11-18T18:37:16.107+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:37:15.025333+00:00 [queued]>
[2024-11-18T18:37:16.112+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:37:15.025333+00:00 [queued]>
[2024-11-18T18:37:16.112+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-11-18T18:37:16.119+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): train_challenger_model> on 2024-11-18 18:37:15.025333+00:00
[2024-11-18T18:37:16.122+0000] {standard_task_runner.py:60} INFO - Started process 19498 to run task
[2024-11-18T18:37:16.123+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_retrain_challenge_model_v3', 'train_challenger_model', 'manual__2024-11-18T18:37:15.025333+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/retrain_music_model.py', '--cfg-path', '/tmp/tmp9nacfy5d']
[2024-11-18T18:37:16.125+0000] {standard_task_runner.py:88} INFO - Job 99: Subtask train_challenger_model
[2024-11-18T18:37:16.150+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:37:15.025333+00:00 [running]> on host 98017b53a184
[2024-11-18T18:37:16.188+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_retrain_challenge_model_v3' AIRFLOW_CTX_TASK_ID='train_challenger_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T18:37:15.025333+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T18:37:15.025333+00:00'
[2024-11-18T18:37:16.189+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venv6xzwbrsm --system-site-packages --python=python
[2024-11-18T18:37:16.193+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:37:16.564+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 155ms
[2024-11-18T18:37:16.565+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venv6xzwbrsm, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T18:37:16.565+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T18:37:16.565+0000] {process_utils.py:190} INFO -     added seed packages: pip==24.2, setuptools==75.2.0, wheel==0.44.0
[2024-11-18T18:37:16.565+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T18:37:16.582+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv6xzwbrsm/bin/pip install -r /tmp/venv6xzwbrsm/requirements.txt
[2024-11-18T18:37:16.586+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:37:17.413+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venv6xzwbrsm/requirements.txt (line 1))
[2024-11-18T18:37:17.414+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T18:37:17.448+0000] {process_utils.py:190} INFO - Collecting mlflow==2.10.2 (from -r /tmp/venv6xzwbrsm/requirements.txt (line 2))
[2024-11-18T18:37:17.449+0000] {process_utils.py:190} INFO -   Using cached mlflow-2.10.2-py3-none-any.whl.metadata (13 kB)
[2024-11-18T18:37:17.457+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venv6xzwbrsm/requirements.txt (line 3)) (2.0.3)
[2024-11-18T18:37:17.457+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn==1.3.2 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venv6xzwbrsm/requirements.txt (line 4)) (1.3.2)
[2024-11-18T18:37:17.542+0000] {process_utils.py:190} INFO - Collecting tensorflow==2.13.0 (from -r /tmp/venv6xzwbrsm/requirements.txt (line 5))
[2024-11-18T18:37:17.543+0000] {process_utils.py:190} INFO -   Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
[2024-11-18T18:37:17.980+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 1))
[2024-11-18T18:37:17.981+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T18:37:17.983+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 1)) (0.10.0)
[2024-11-18T18:37:18.002+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 1))
[2024-11-18T18:37:18.003+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:37:18.006+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (8.1.7)
[2024-11-18T18:37:18.006+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (3.1.0)
[2024-11-18T18:37:18.019+0000] {process_utils.py:190} INFO - Collecting entrypoints<1 (from mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2))
[2024-11-18T18:37:18.020+0000] {process_utils.py:190} INFO -   Using cached entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
[2024-11-18T18:37:18.021+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=2.1.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (3.1.43)
[2024-11-18T18:37:18.021+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (6.0.1)
[2024-11-18T18:37:18.022+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<5,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (4.25.2)
[2024-11-18T18:37:18.022+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz<2024 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T18:37:18.022+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (2.31.0)
[2024-11-18T18:37:18.022+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (23.2)
[2024-11-18T18:37:18.023+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (6.11.0)
[2024-11-18T18:37:18.023+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (0.4.4)
[2024-11-18T18:37:18.023+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (1.13.1)
[2024-11-18T18:37:18.024+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (7.0.0)
[2024-11-18T18:37:18.024+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (2.2.5)
[2024-11-18T18:37:18.025+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (1.24.4)
[2024-11-18T18:37:18.025+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (1.10.1)
[2024-11-18T18:37:18.036+0000] {process_utils.py:190} INFO - Collecting querystring-parser<2 (from mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2))
[2024-11-18T18:37:18.037+0000] {process_utils.py:190} INFO -   Using cached querystring_parser-1.2.4-py2.py3-none-any.whl.metadata (559 bytes)
[2024-11-18T18:37:18.038+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (1.4.51)
[2024-11-18T18:37:18.039+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow<16,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (14.0.2)
[2024-11-18T18:37:18.039+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (3.5.2)
[2024-11-18T18:37:18.039+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (3.7.5)
[2024-11-18T18:37:18.040+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<22 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (21.2.0)
[2024-11-18T18:37:18.040+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (3.1.3)
[2024-11-18T18:37:18.061+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venv6xzwbrsm/requirements.txt (line 3)) (2.8.2)
[2024-11-18T18:37:18.062+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venv6xzwbrsm/requirements.txt (line 3)) (2023.4)
[2024-11-18T18:37:18.067+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 4)) (1.4.2)
[2024-11-18T18:37:18.067+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 4)) (3.5.0)
[2024-11-18T18:37:18.083+0000] {process_utils.py:190} INFO - Collecting absl-py>=1.0.0 (from tensorflow==2.13.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 5))
[2024-11-18T18:37:18.084+0000] {process_utils.py:190} INFO -   Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
[2024-11-18T18:37:18.102+0000] {process_utils.py:190} INFO - Collecting astunparse>=1.6.0 (from tensorflow==2.13.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 5))
[2024-11-18T18:37:18.103+0000] {process_utils.py:190} INFO -   Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
[2024-11-18T18:37:18.118+0000] {process_utils.py:190} INFO - Collecting flatbuffers>=23.1.21 (from tensorflow==2.13.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 5))
[2024-11-18T18:37:18.120+0000] {process_utils.py:190} INFO -   Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
[2024-11-18T18:37:18.138+0000] {process_utils.py:190} INFO - Collecting gast<=0.4.0,>=0.2.1 (from tensorflow==2.13.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 5))
[2024-11-18T18:37:18.139+0000] {process_utils.py:190} INFO -   Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
[2024-11-18T18:37:18.152+0000] {process_utils.py:190} INFO - Collecting google-pasta>=0.1.1 (from tensorflow==2.13.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 5))
[2024-11-18T18:37:18.153+0000] {process_utils.py:190} INFO -   Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
[2024-11-18T18:37:18.154+0000] {process_utils.py:190} INFO - Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 5)) (1.60.0)
[2024-11-18T18:37:18.190+0000] {process_utils.py:190} INFO - Collecting h5py>=2.9.0 (from tensorflow==2.13.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 5))
[2024-11-18T18:37:18.192+0000] {process_utils.py:190} INFO -   Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
[2024-11-18T18:37:18.217+0000] {process_utils.py:190} INFO - Collecting keras<2.14,>=2.13.1 (from tensorflow==2.13.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 5))
[2024-11-18T18:37:18.218+0000] {process_utils.py:190} INFO -   Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
[2024-11-18T18:37:18.235+0000] {process_utils.py:190} INFO - Collecting libclang>=13.0.0 (from tensorflow==2.13.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 5))
[2024-11-18T18:37:18.237+0000] {process_utils.py:190} INFO -   Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
[2024-11-18T18:37:18.403+0000] {process_utils.py:190} INFO - Collecting numpy<2 (from mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2))
[2024-11-18T18:37:18.404+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-11-18T18:37:18.417+0000] {process_utils.py:190} INFO - Collecting opt-einsum>=2.3.2 (from tensorflow==2.13.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 5))
[2024-11-18T18:37:18.419+0000] {process_utils.py:190} INFO -   Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
[2024-11-18T18:37:18.420+0000] {process_utils.py:190} INFO - Requirement already satisfied: setuptools in /tmp/venv6xzwbrsm/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 5)) (75.2.0)
[2024-11-18T18:37:18.420+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.12.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 5)) (1.16.0)
[2024-11-18T18:37:18.440+0000] {process_utils.py:190} INFO - Collecting tensorboard<2.14,>=2.13 (from tensorflow==2.13.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 5))
[2024-11-18T18:37:18.441+0000] {process_utils.py:190} INFO -   Using cached tensorboard-2.13.0-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:37:18.457+0000] {process_utils.py:190} INFO - Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow==2.13.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 5))
[2024-11-18T18:37:18.458+0000] {process_utils.py:190} INFO -   Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
[2024-11-18T18:37:18.459+0000] {process_utils.py:190} INFO - Requirement already satisfied: termcolor>=1.1.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 5)) (2.4.0)
[2024-11-18T18:37:18.477+0000] {process_utils.py:190} INFO - Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow==2.13.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 5))
[2024-11-18T18:37:18.478+0000] {process_utils.py:190} INFO -   Using cached typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
[2024-11-18T18:37:18.479+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt>=1.11.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 5)) (1.16.0)
[2024-11-18T18:37:18.507+0000] {process_utils.py:190} INFO - Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow==2.13.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 5))
[2024-11-18T18:37:18.508+0000] {process_utils.py:190} INFO -   Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
[2024-11-18T18:37:18.512+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (1.3.0)
[2024-11-18T18:37:18.516+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (5.13.0)
[2024-11-18T18:37:18.517+0000] {process_utils.py:190} INFO - Requirement already satisfied: wheel<1.0,>=0.23.0 in /tmp/venv6xzwbrsm/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow==2.13.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 5)) (0.44.0)
[2024-11-18T18:37:18.518+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 1)) (1.26.18)
[2024-11-18T18:37:18.524+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (2.2.3)
[2024-11-18T18:37:18.524+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (2.1.2)
[2024-11-18T18:37:18.530+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (4.0.11)
[2024-11-18T18:37:18.538+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (3.17.0)
[2024-11-18T18:37:18.539+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (2.1.3)
[2024-11-18T18:37:18.547+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (1.1.1)
[2024-11-18T18:37:18.548+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (0.12.1)
[2024-11-18T18:37:18.548+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (4.54.1)
[2024-11-18T18:37:18.548+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (1.4.7)
[2024-11-18T18:37:18.556+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (10.4.0)
[2024-11-18T18:37:18.556+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (3.1.1)
[2024-11-18T18:37:18.575+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (3.3.2)
[2024-11-18T18:37:18.576+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (3.6)
[2024-11-18T18:37:18.576+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (2023.11.17)
[2024-11-18T18:37:18.806+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (3.0.3)
[2024-11-18T18:37:18.812+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth<3,>=1.6.3 in /home/***/.local/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 5)) (2.26.2)
[2024-11-18T18:37:18.828+0000] {process_utils.py:190} INFO - Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 5))
[2024-11-18T18:37:18.830+0000] {process_utils.py:190} INFO -   Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
[2024-11-18T18:37:18.854+0000] {process_utils.py:190} INFO - Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 5))
[2024-11-18T18:37:18.855+0000] {process_utils.py:190} INFO -   Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
[2024-11-18T18:37:18.902+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venv6xzwbrsm/requirements.txt (line 2)) (5.0.1)
[2024-11-18T18:37:18.905+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 5)) (5.3.2)
[2024-11-18T18:37:18.905+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 5)) (0.3.0)
[2024-11-18T18:37:18.906+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 5)) (4.9)
[2024-11-18T18:37:18.907+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 5)) (1.3.1)
[2024-11-18T18:37:18.935+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 5)) (0.5.1)
[2024-11-18T18:37:18.936+0000] {process_utils.py:190} INFO - Requirement already satisfied: oauthlib>=3.0.0 in /home/***/.local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv6xzwbrsm/requirements.txt (line 5)) (3.2.2)
[2024-11-18T18:37:18.945+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T18:37:18.946+0000] {process_utils.py:190} INFO - Using cached mlflow-2.10.2-py3-none-any.whl (19.5 MB)
[2024-11-18T18:37:18.955+0000] {process_utils.py:190} INFO - Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.1 MB)
[2024-11-18T18:37:19.172+0000] {process_utils.py:190} INFO - Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
[2024-11-18T18:37:19.173+0000] {process_utils.py:190} INFO - Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
[2024-11-18T18:37:19.174+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T18:37:19.180+0000] {process_utils.py:190} INFO - Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
[2024-11-18T18:37:19.181+0000] {process_utils.py:190} INFO - Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
[2024-11-18T18:37:19.183+0000] {process_utils.py:190} INFO - Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
[2024-11-18T18:37:19.184+0000] {process_utils.py:190} INFO - Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
[2024-11-18T18:37:19.185+0000] {process_utils.py:190} INFO - Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
[2024-11-18T18:37:19.189+0000] {process_utils.py:190} INFO - Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)
[2024-11-18T18:37:19.191+0000] {process_utils.py:190} INFO - Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
[2024-11-18T18:37:19.204+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-11-18T18:37:19.213+0000] {process_utils.py:190} INFO - Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
[2024-11-18T18:37:19.214+0000] {process_utils.py:190} INFO - Using cached querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
[2024-11-18T18:37:19.215+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T18:37:19.216+0000] {process_utils.py:190} INFO - Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
[2024-11-18T18:37:19.220+0000] {process_utils.py:190} INFO - Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
[2024-11-18T18:37:19.221+0000] {process_utils.py:190} INFO - Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
[2024-11-18T18:37:19.224+0000] {process_utils.py:190} INFO - Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
[2024-11-18T18:37:19.225+0000] {process_utils.py:190} INFO - Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
[2024-11-18T18:37:19.226+0000] {process_utils.py:190} INFO - Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
[2024-11-18T18:37:20.434+0000] {process_utils.py:190} INFO - Installing collected packages: libclang, flatbuffers, typing-extensions, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, querystring-parser, opt-einsum, numpy, keras, google-pasta, gast, entrypoints, astunparse, absl-py, h5py, botocore, s3transfer, google-auth-oauthlib, tensorboard, mlflow, boto3, tensorflow
[2024-11-18T18:37:20.669+0000] {process_utils.py:190} INFO -   Attempting uninstall: typing-extensions
[2024-11-18T18:37:20.671+0000] {process_utils.py:190} INFO -     Found existing installation: typing_extensions 4.9.0
[2024-11-18T18:37:20.671+0000] {process_utils.py:190} INFO -     Not uninstalling typing-extensions at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv6xzwbrsm
[2024-11-18T18:37:20.672+0000] {process_utils.py:190} INFO -     Can't uninstall 'typing_extensions'. No files were found to uninstall.
[2024-11-18T18:37:20.928+0000] {process_utils.py:190} INFO -   Attempting uninstall: numpy
[2024-11-18T18:37:20.930+0000] {process_utils.py:190} INFO -     Found existing installation: numpy 1.24.4
[2024-11-18T18:37:20.930+0000] {process_utils.py:190} INFO -     Not uninstalling numpy at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv6xzwbrsm
[2024-11-18T18:37:20.930+0000] {process_utils.py:190} INFO -     Can't uninstall 'numpy'. No files were found to uninstall.
[2024-11-18T18:37:22.530+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T18:37:22.531+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T18:37:22.531+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv6xzwbrsm
[2024-11-18T18:37:22.531+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T18:37:22.913+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T18:37:22.914+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T18:37:22.914+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv6xzwbrsm
[2024-11-18T18:37:22.915+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T18:37:22.935+0000] {process_utils.py:190} INFO -   Attempting uninstall: google-auth-oauthlib
[2024-11-18T18:37:22.936+0000] {process_utils.py:190} INFO -     Found existing installation: google-auth-oauthlib 1.2.0
[2024-11-18T18:37:22.937+0000] {process_utils.py:190} INFO -     Not uninstalling google-auth-oauthlib at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv6xzwbrsm
[2024-11-18T18:37:22.937+0000] {process_utils.py:190} INFO -     Can't uninstall 'google-auth-oauthlib'. No files were found to uninstall.
[2024-11-18T18:37:23.131+0000] {process_utils.py:190} INFO -   Attempting uninstall: mlflow
[2024-11-18T18:37:23.133+0000] {process_utils.py:190} INFO -     Found existing installation: mlflow 2.17.0
[2024-11-18T18:37:23.133+0000] {process_utils.py:190} INFO -     Not uninstalling mlflow at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv6xzwbrsm
[2024-11-18T18:37:23.133+0000] {process_utils.py:190} INFO -     Can't uninstall 'mlflow'. No files were found to uninstall.
[2024-11-18T18:37:23.667+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T18:37:23.668+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T18:37:23.668+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv6xzwbrsm
[2024-11-18T18:37:23.672+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T18:37:30.599+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T18:37:30.600+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T18:37:30.600+0000] {process_utils.py:190} INFO - azure-core 1.29.6 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:37:30.600+0000] {process_utils.py:190} INFO - azure-mgmt-keyvault 10.3.1 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:37:30.601+0000] {process_utils.py:190} INFO - azure-mgmt-network 27.0.0 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:37:30.601+0000] {process_utils.py:190} INFO - graphene 3.4 requires typing-extensions<5,>=4.7.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:37:30.601+0000] {process_utils.py:190} INFO - pydantic 2.5.3 requires typing-extensions>=4.6.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:37:30.601+0000] {process_utils.py:190} INFO - pydantic-core 2.14.6 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:37:30.601+0000] {process_utils.py:190} INFO - Successfully installed absl-py-2.1.0 astunparse-1.6.3 boto3-1.28.0 botocore-1.31.85 entrypoints-0.4 flatbuffers-24.3.25 gast-0.4.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 h5py-3.11.0 keras-2.13.1 libclang-18.1.1 mlflow-2.10.2 numpy-1.24.3 opt-einsum-3.4.0 querystring-parser-1.2.4 s3transfer-0.6.2 tensorboard-2.13.0 tensorboard-data-server-0.7.2 tensorflow-2.13.0 tensorflow-estimator-2.13.0 tensorflow-io-gcs-filesystem-0.34.0 typing-extensions-4.5.0
[2024-11-18T18:37:30.666+0000] {process_utils.py:190} INFO - 
[2024-11-18T18:37:30.666+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 24.2 -> 24.3.1
[2024-11-18T18:37:30.667+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T18:37:30.863+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv6xzwbrsm/bin/python /tmp/venv-callaolaf3xo/script.py /tmp/venv-callaolaf3xo/script.in /tmp/venv-callaolaf3xo/script.out /tmp/venv-callaolaf3xo/string_args.txt /tmp/venv-callaolaf3xo/termination.log
[2024-11-18T18:37:30.866+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:37:31.783+0000] {process_utils.py:190} INFO - 2024-11-18 18:37:31.783639: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-11-18T18:37:31.784+0000] {process_utils.py:190} INFO - 2024-11-18 18:37:31.784867: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T18:37:31.806+0000] {process_utils.py:190} INFO - 2024-11-18 18:37:31.806211: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T18:37:31.806+0000] {process_utils.py:190} INFO - 2024-11-18 18:37:31.806776: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-11-18T18:37:31.807+0000] {process_utils.py:190} INFO - To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-11-18T18:37:32.300+0000] {process_utils.py:190} INFO - 2024-11-18 18:37:32.300655: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-11-18T18:37:33.304+0000] {process_utils.py:190} INFO - Epoch 1/10
[2024-11-18T18:37:34.213+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 2:45 - loss: 0.3854 46/575 [=>............................] - ETA: 0s - loss: 0.1969   95/575 [===>..........................] - ETA: 0s - loss: 0.1340176/575 [========>.....................] - ETA: 0s - loss: 0.0951259/575 [============>.................] - ETA: 0s - loss: 0.0766341/575 [================>.............] - ETA: 0s - loss: 0.0657423/575 [=====================>........] - ETA: 0s - loss: 0.0580504/575 [=========================>....] - ETA: 0s - loss: 0.0526575/575 [==============================] - 1s 1ms/step - loss: 0.0488 - val_loss: 0.0092
[2024-11-18T18:37:34.213+0000] {process_utils.py:190} INFO - Epoch 2/10
[2024-11-18T18:37:34.644+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0288 82/575 [===>..........................] - ETA: 0s - loss: 0.0208163/575 [=======>......................] - ETA: 0s - loss: 0.0198245/575 [===========>..................] - ETA: 0s - loss: 0.0188325/575 [===============>..............] - ETA: 0s - loss: 0.0182407/575 [====================>.........] - ETA: 0s - loss: 0.0176489/575 [========================>.....] - ETA: 0s - loss: 0.0171572/575 [============================>.] - ETA: 0s - loss: 0.0167575/575 [==============================] - 0s 749us/step - loss: 0.0167 - val_loss: 0.0050
[2024-11-18T18:37:34.644+0000] {process_utils.py:190} INFO - Epoch 3/10
[2024-11-18T18:37:35.078+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0139 82/575 [===>..........................] - ETA: 0s - loss: 0.0135164/575 [=======>......................] - ETA: 0s - loss: 0.0133246/575 [===========>..................] - ETA: 0s - loss: 0.0131328/575 [================>.............] - ETA: 0s - loss: 0.0129399/575 [===================>..........] - ETA: 0s - loss: 0.0127486/575 [========================>.....] - ETA: 0s - loss: 0.0124569/575 [============================>.] - ETA: 0s - loss: 0.0122575/575 [==============================] - 0s 754us/step - loss: 0.0121 - val_loss: 0.0039
[2024-11-18T18:37:35.078+0000] {process_utils.py:190} INFO - Epoch 4/10
[2024-11-18T18:37:35.507+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0100 81/575 [===>..........................] - ETA: 0s - loss: 0.0106164/575 [=======>......................] - ETA: 0s - loss: 0.0103247/575 [===========>..................] - ETA: 0s - loss: 0.0102330/575 [================>.............] - ETA: 0s - loss: 0.0100412/575 [====================>.........] - ETA: 0s - loss: 0.0099497/575 [========================>.....] - ETA: 0s - loss: 0.0098575/575 [==============================] - 0s 746us/step - loss: 0.0097 - val_loss: 0.0035
[2024-11-18T18:37:35.508+0000] {process_utils.py:190} INFO - Epoch 5/10
[2024-11-18T18:37:35.936+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0079 83/575 [===>..........................] - ETA: 0s - loss: 0.0089165/575 [=======>......................] - ETA: 0s - loss: 0.0088248/575 [===========>..................] - ETA: 0s - loss: 0.0086330/575 [================>.............] - ETA: 0s - loss: 0.0086411/575 [====================>.........] - ETA: 0s - loss: 0.0086493/575 [========================>.....] - ETA: 0s - loss: 0.0085575/575 [==============================] - 0s 745us/step - loss: 0.0084 - val_loss: 0.0030
[2024-11-18T18:37:35.937+0000] {process_utils.py:190} INFO - Epoch 6/10
[2024-11-18T18:37:36.380+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0070 83/575 [===>..........................] - ETA: 0s - loss: 0.0081165/575 [=======>......................] - ETA: 0s - loss: 0.0081248/575 [===========>..................] - ETA: 0s - loss: 0.0079325/575 [===============>..............] - ETA: 0s - loss: 0.0079396/575 [===================>..........] - ETA: 0s - loss: 0.0078472/575 [=======================>......] - ETA: 0s - loss: 0.0078553/575 [===========================>..] - ETA: 0s - loss: 0.0077575/575 [==============================] - 0s 770us/step - loss: 0.0077 - val_loss: 0.0029
[2024-11-18T18:37:36.380+0000] {process_utils.py:190} INFO - Epoch 7/10
[2024-11-18T18:37:36.811+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0100 79/575 [===>..........................] - ETA: 0s - loss: 0.0075158/575 [=======>......................] - ETA: 0s - loss: 0.0075243/575 [===========>..................] - ETA: 0s - loss: 0.0073325/575 [===============>..............] - ETA: 0s - loss: 0.0073407/575 [====================>.........] - ETA: 0s - loss: 0.0073491/575 [========================>.....] - ETA: 0s - loss: 0.0073573/575 [============================>.] - ETA: 0s - loss: 0.0072575/575 [==============================] - 0s 749us/step - loss: 0.0072 - val_loss: 0.0027
[2024-11-18T18:37:36.811+0000] {process_utils.py:190} INFO - Epoch 8/10
[2024-11-18T18:37:37.239+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0072 83/575 [===>..........................] - ETA: 0s - loss: 0.0070165/575 [=======>......................] - ETA: 0s - loss: 0.0071249/575 [===========>..................] - ETA: 0s - loss: 0.0070330/575 [================>.............] - ETA: 0s - loss: 0.0069415/575 [====================>.........] - ETA: 0s - loss: 0.0069498/575 [========================>.....] - ETA: 0s - loss: 0.0069575/575 [==============================] - 0s 743us/step - loss: 0.0069 - val_loss: 0.0026
[2024-11-18T18:37:37.239+0000] {process_utils.py:190} INFO - Epoch 9/10
[2024-11-18T18:37:37.682+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0058 81/575 [===>..........................] - ETA: 0s - loss: 0.0069161/575 [=======>......................] - ETA: 0s - loss: 0.0068242/575 [===========>..................] - ETA: 0s - loss: 0.0068322/575 [===============>..............] - ETA: 0s - loss: 0.0068400/575 [===================>..........] - ETA: 0s - loss: 0.0068476/575 [=======================>......] - ETA: 0s - loss: 0.0068553/575 [===========================>..] - ETA: 0s - loss: 0.0067575/575 [==============================] - 0s 770us/step - loss: 0.0067 - val_loss: 0.0022
[2024-11-18T18:37:37.682+0000] {process_utils.py:190} INFO - Epoch 10/10
[2024-11-18T18:37:38.141+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0069 79/575 [===>..........................] - ETA: 0s - loss: 0.0067155/575 [=======>......................] - ETA: 0s - loss: 0.0066232/575 [===========>..................] - ETA: 0s - loss: 0.0067310/575 [===============>..............] - ETA: 0s - loss: 0.0065387/575 [===================>..........] - ETA: 0s - loss: 0.0065463/575 [=======================>......] - ETA: 0s - loss: 0.0066539/575 [===========================>..] - ETA: 0s - loss: 0.0065575/575 [==============================] - 0s 798us/step - loss: 0.0065 - val_loss: 0.0022
[2024-11-18T18:37:38.531+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 29s 94/719 [==>...........................] - ETA: 0s 203/719 [=======>......................] - ETA: 0s324/719 [============>.................] - ETA: 0s442/719 [=================>............] - ETA: 0s552/719 [======================>.......] - ETA: 0s661/719 [==========================>...] - ETA: 0s719/719 [==============================] - 0s 457us/step
[2024-11-18T18:37:39.103+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 7s105/719 [===>..........................] - ETA: 0s210/719 [=======>......................] - ETA: 0s316/719 [============>.................] - ETA: 0s422/719 [================>.............] - ETA: 0s529/719 [=====================>........] - ETA: 0s633/719 [=========================>....] - ETA: 0s719/719 [==============================] - 0s 483us/step
[2024-11-18T18:37:39.395+0000] {process_utils.py:190} INFO - 2024/11/18 18:37:39 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.
[2024-11-18T18:37:39.730+0000] {process_utils.py:190} INFO - [[34m2024-11-18T18:37:39.729+0000[0m] {[34mbuilder_impl.py:[0m804} INFO[0m - Assets written to: /tmp/tmpnbe0bk2r/model/data/model/assets[0m
[2024-11-18T18:37:42.325+0000] {process_utils.py:190} INFO - /tmp/venv6xzwbrsm/lib/python3.8/site-packages/_distutils_hack/__init__.py:31 UserWarning: Setuptools is replacing distutils. Support for replacing an already imported distutils is deprecated. In the future, this condition will fail. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
[2024-11-18T18:37:42.362+0000] {process_utils.py:190} INFO - [[34m2024-11-18T18:37:42.362+0000[0m] {[34mcredentials.py:[0m1124} INFO[0m - Found credentials in environment variables.[0m
[2024-11-18T18:37:42.470+0000] {process_utils.py:190} INFO - Registered model 'spotify_model_prod' already exists. Creating a new version of this model...
[2024-11-18T18:37:42.471+0000] {process_utils.py:190} INFO - 2024/11/18 18:37:42 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: spotify_model_prod, version 9
[2024-11-18T18:37:42.471+0000] {process_utils.py:190} INFO - Created version '9' of model 'spotify_model_prod'.
[2024-11-18T18:37:42.472+0000] {process_utils.py:190} INFO - /tmp/venv6xzwbrsm/lib/python3.8/site-packages/keras/src/engine/training.py:3000 UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
[2024-11-18T18:37:43.681+0000] {python.py:201} INFO - Done. Returned value was: Challenger model trained and logged.
[2024-11-18T18:37:43.700+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=spotify_retrain_challenge_model_v3, task_id=train_challenger_model, execution_date=20241118T183715, start_date=20241118T183716, end_date=20241118T183743
[2024-11-18T18:37:43.728+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-11-18T18:37:43.739+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
