[2024-11-18T21:33:26.155+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T21:27:58.453911+00:00 [queued]>
[2024-11-18T21:33:26.160+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T21:27:58.453911+00:00 [queued]>
[2024-11-18T21:33:26.161+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-11-18T21:33:26.168+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): train_challenger_model> on 2024-11-18 21:27:58.453911+00:00
[2024-11-18T21:33:26.171+0000] {standard_task_runner.py:60} INFO - Started process 7970 to run task
[2024-11-18T21:33:26.172+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_retrain_challenge_model_v3', 'train_challenger_model', 'manual__2024-11-18T21:27:58.453911+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/retrain_music_model.py', '--cfg-path', '/tmp/tmpv_mn5xx9']
[2024-11-18T21:33:26.174+0000] {standard_task_runner.py:88} INFO - Job 139: Subtask train_challenger_model
[2024-11-18T21:33:26.199+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T21:27:58.453911+00:00 [running]> on host 46787693bc19
[2024-11-18T21:33:26.243+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_retrain_challenge_model_v3' AIRFLOW_CTX_TASK_ID='train_challenger_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T21:27:58.453911+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T21:27:58.453911+00:00'
[2024-11-18T21:33:26.244+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvbnvdq_j3 --system-site-packages --python=python
[2024-11-18T21:33:26.248+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T21:33:26.575+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 118ms
[2024-11-18T21:33:26.575+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvbnvdq_j3, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T21:33:26.576+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T21:33:26.576+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-11-18T21:33:26.576+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T21:33:26.592+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvbnvdq_j3/bin/pip install -r /tmp/venvbnvdq_j3/requirements.txt
[2024-11-18T21:33:26.596+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T21:33:27.521+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venvbnvdq_j3/requirements.txt (line 1))
[2024-11-18T21:33:27.522+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T21:33:27.561+0000] {process_utils.py:190} INFO - Collecting mlflow==2.10.2 (from -r /tmp/venvbnvdq_j3/requirements.txt (line 2))
[2024-11-18T21:33:27.562+0000] {process_utils.py:190} INFO -   Using cached mlflow-2.10.2-py3-none-any.whl.metadata (13 kB)
[2024-11-18T21:33:27.563+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvbnvdq_j3/requirements.txt (line 3)) (2.0.3)
[2024-11-18T21:33:27.563+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn==1.3.2 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvbnvdq_j3/requirements.txt (line 4)) (1.3.2)
[2024-11-18T21:33:27.663+0000] {process_utils.py:190} INFO - Collecting tensorflow==2.13.0 (from -r /tmp/venvbnvdq_j3/requirements.txt (line 5))
[2024-11-18T21:33:27.664+0000] {process_utils.py:190} INFO -   Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
[2024-11-18T21:33:28.093+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 1))
[2024-11-18T21:33:28.094+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T21:33:28.095+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 1)) (0.10.0)
[2024-11-18T21:33:28.117+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 1))
[2024-11-18T21:33:28.119+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T21:33:28.173+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (8.1.7)
[2024-11-18T21:33:28.173+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (3.1.0)
[2024-11-18T21:33:28.189+0000] {process_utils.py:190} INFO - Collecting entrypoints<1 (from mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2))
[2024-11-18T21:33:28.191+0000] {process_utils.py:190} INFO -   Using cached entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
[2024-11-18T21:33:28.192+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=2.1.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (3.1.43)
[2024-11-18T21:33:28.192+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (6.0.1)
[2024-11-18T21:33:28.193+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<5,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (4.25.2)
[2024-11-18T21:33:28.193+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz<2024 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T21:33:28.194+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (2.31.0)
[2024-11-18T21:33:28.194+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (23.2)
[2024-11-18T21:33:28.195+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (6.11.0)
[2024-11-18T21:33:28.195+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (0.4.4)
[2024-11-18T21:33:28.196+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (1.13.1)
[2024-11-18T21:33:28.196+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (7.0.0)
[2024-11-18T21:33:28.197+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (2.2.5)
[2024-11-18T21:33:28.197+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (1.24.4)
[2024-11-18T21:33:28.197+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (1.10.1)
[2024-11-18T21:33:28.214+0000] {process_utils.py:190} INFO - Collecting querystring-parser<2 (from mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2))
[2024-11-18T21:33:28.216+0000] {process_utils.py:190} INFO -   Using cached querystring_parser-1.2.4-py2.py3-none-any.whl.metadata (559 bytes)
[2024-11-18T21:33:28.217+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (1.4.51)
[2024-11-18T21:33:28.217+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow<16,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (14.0.2)
[2024-11-18T21:33:28.218+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (3.5.2)
[2024-11-18T21:33:28.218+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (3.7.5)
[2024-11-18T21:33:28.219+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<22 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (21.2.0)
[2024-11-18T21:33:28.220+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (3.1.3)
[2024-11-18T21:33:28.272+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvbnvdq_j3/requirements.txt (line 3)) (2.8.2)
[2024-11-18T21:33:28.272+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvbnvdq_j3/requirements.txt (line 3)) (2023.4)
[2024-11-18T21:33:28.292+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 4)) (1.4.2)
[2024-11-18T21:33:28.292+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 4)) (3.5.0)
[2024-11-18T21:33:28.325+0000] {process_utils.py:190} INFO - Collecting absl-py>=1.0.0 (from tensorflow==2.13.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 5))
[2024-11-18T21:33:28.326+0000] {process_utils.py:190} INFO -   Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
[2024-11-18T21:33:28.341+0000] {process_utils.py:190} INFO - Collecting astunparse>=1.6.0 (from tensorflow==2.13.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 5))
[2024-11-18T21:33:28.343+0000] {process_utils.py:190} INFO -   Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
[2024-11-18T21:33:28.361+0000] {process_utils.py:190} INFO - Collecting flatbuffers>=23.1.21 (from tensorflow==2.13.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 5))
[2024-11-18T21:33:28.362+0000] {process_utils.py:190} INFO -   Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
[2024-11-18T21:33:28.383+0000] {process_utils.py:190} INFO - Collecting gast<=0.4.0,>=0.2.1 (from tensorflow==2.13.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 5))
[2024-11-18T21:33:28.384+0000] {process_utils.py:190} INFO -   Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
[2024-11-18T21:33:28.401+0000] {process_utils.py:190} INFO - Collecting google-pasta>=0.1.1 (from tensorflow==2.13.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 5))
[2024-11-18T21:33:28.402+0000] {process_utils.py:190} INFO -   Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
[2024-11-18T21:33:28.403+0000] {process_utils.py:190} INFO - Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 5)) (1.60.0)
[2024-11-18T21:33:28.443+0000] {process_utils.py:190} INFO - Collecting h5py>=2.9.0 (from tensorflow==2.13.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 5))
[2024-11-18T21:33:28.445+0000] {process_utils.py:190} INFO -   Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
[2024-11-18T21:33:28.473+0000] {process_utils.py:190} INFO - Collecting keras<2.14,>=2.13.1 (from tensorflow==2.13.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 5))
[2024-11-18T21:33:28.474+0000] {process_utils.py:190} INFO -   Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
[2024-11-18T21:33:28.495+0000] {process_utils.py:190} INFO - Collecting libclang>=13.0.0 (from tensorflow==2.13.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 5))
[2024-11-18T21:33:28.496+0000] {process_utils.py:190} INFO -   Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
[2024-11-18T21:33:28.640+0000] {process_utils.py:190} INFO - Collecting numpy<2 (from mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2))
[2024-11-18T21:33:28.641+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-11-18T21:33:28.658+0000] {process_utils.py:190} INFO - Collecting opt-einsum>=2.3.2 (from tensorflow==2.13.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 5))
[2024-11-18T21:33:28.660+0000] {process_utils.py:190} INFO -   Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
[2024-11-18T21:33:28.661+0000] {process_utils.py:190} INFO - Requirement already satisfied: setuptools in /tmp/venvbnvdq_j3/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 5)) (69.0.2)
[2024-11-18T21:33:28.661+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.12.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 5)) (1.16.0)
[2024-11-18T21:33:28.684+0000] {process_utils.py:190} INFO - Collecting tensorboard<2.14,>=2.13 (from tensorflow==2.13.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 5))
[2024-11-18T21:33:28.685+0000] {process_utils.py:190} INFO -   Using cached tensorboard-2.13.0-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T21:33:28.704+0000] {process_utils.py:190} INFO - Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow==2.13.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 5))
[2024-11-18T21:33:28.705+0000] {process_utils.py:190} INFO -   Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
[2024-11-18T21:33:28.706+0000] {process_utils.py:190} INFO - Requirement already satisfied: termcolor>=1.1.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 5)) (2.4.0)
[2024-11-18T21:33:28.728+0000] {process_utils.py:190} INFO - Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow==2.13.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 5))
[2024-11-18T21:33:28.729+0000] {process_utils.py:190} INFO -   Using cached typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
[2024-11-18T21:33:28.730+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt>=1.11.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 5)) (1.16.0)
[2024-11-18T21:33:28.783+0000] {process_utils.py:190} INFO - Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow==2.13.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 5))
[2024-11-18T21:33:28.784+0000] {process_utils.py:190} INFO -   Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
[2024-11-18T21:33:28.791+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (1.3.0)
[2024-11-18T21:33:28.795+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (5.13.0)
[2024-11-18T21:33:28.798+0000] {process_utils.py:190} INFO - Requirement already satisfied: wheel<1.0,>=0.23.0 in /tmp/venvbnvdq_j3/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow==2.13.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 5)) (0.42.0)
[2024-11-18T21:33:28.803+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 1)) (1.26.18)
[2024-11-18T21:33:28.817+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (2.2.3)
[2024-11-18T21:33:28.818+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (2.1.2)
[2024-11-18T21:33:28.834+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (4.0.11)
[2024-11-18T21:33:28.861+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (3.17.0)
[2024-11-18T21:33:28.864+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (2.1.3)
[2024-11-18T21:33:28.888+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (1.1.1)
[2024-11-18T21:33:28.889+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (0.12.1)
[2024-11-18T21:33:28.889+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (4.54.1)
[2024-11-18T21:33:28.889+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (1.4.7)
[2024-11-18T21:33:28.899+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (10.4.0)
[2024-11-18T21:33:28.901+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (3.1.1)
[2024-11-18T21:33:28.943+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (3.3.2)
[2024-11-18T21:33:28.944+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (3.6)
[2024-11-18T21:33:28.945+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (2023.11.17)
[2024-11-18T21:33:29.182+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (3.0.3)
[2024-11-18T21:33:29.199+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth<3,>=1.6.3 in /home/***/.local/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 5)) (2.26.2)
[2024-11-18T21:33:29.222+0000] {process_utils.py:190} INFO - Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 5))
[2024-11-18T21:33:29.223+0000] {process_utils.py:190} INFO -   Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
[2024-11-18T21:33:29.252+0000] {process_utils.py:190} INFO - Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 5))
[2024-11-18T21:33:29.253+0000] {process_utils.py:190} INFO -   Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
[2024-11-18T21:33:29.397+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvbnvdq_j3/requirements.txt (line 2)) (5.0.1)
[2024-11-18T21:33:29.408+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 5)) (5.3.2)
[2024-11-18T21:33:29.408+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 5)) (0.3.0)
[2024-11-18T21:33:29.409+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 5)) (4.9)
[2024-11-18T21:33:29.416+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 5)) (1.3.1)
[2024-11-18T21:33:29.547+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 5)) (0.5.1)
[2024-11-18T21:33:29.554+0000] {process_utils.py:190} INFO - Requirement already satisfied: oauthlib>=3.0.0 in /home/***/.local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvbnvdq_j3/requirements.txt (line 5)) (3.2.2)
[2024-11-18T21:33:29.587+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T21:33:29.589+0000] {process_utils.py:190} INFO - Using cached mlflow-2.10.2-py3-none-any.whl (19.5 MB)
[2024-11-18T21:33:29.608+0000] {process_utils.py:190} INFO - Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.1 MB)
[2024-11-18T21:33:30.067+0000] {process_utils.py:190} INFO - Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
[2024-11-18T21:33:30.069+0000] {process_utils.py:190} INFO - Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
[2024-11-18T21:33:30.070+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T21:33:30.082+0000] {process_utils.py:190} INFO - Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
[2024-11-18T21:33:30.083+0000] {process_utils.py:190} INFO - Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
[2024-11-18T21:33:30.084+0000] {process_utils.py:190} INFO - Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
[2024-11-18T21:33:30.086+0000] {process_utils.py:190} INFO - Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
[2024-11-18T21:33:30.087+0000] {process_utils.py:190} INFO - Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
[2024-11-18T21:33:30.092+0000] {process_utils.py:190} INFO - Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)
[2024-11-18T21:33:30.096+0000] {process_utils.py:190} INFO - Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
[2024-11-18T21:33:30.120+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-11-18T21:33:30.137+0000] {process_utils.py:190} INFO - Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
[2024-11-18T21:33:30.138+0000] {process_utils.py:190} INFO - Using cached querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
[2024-11-18T21:33:30.139+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T21:33:30.140+0000] {process_utils.py:190} INFO - Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
[2024-11-18T21:33:30.147+0000] {process_utils.py:190} INFO - Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
[2024-11-18T21:33:30.148+0000] {process_utils.py:190} INFO - Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
[2024-11-18T21:33:30.152+0000] {process_utils.py:190} INFO - Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
[2024-11-18T21:33:30.153+0000] {process_utils.py:190} INFO - Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
[2024-11-18T21:33:30.154+0000] {process_utils.py:190} INFO - Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
[2024-11-18T21:33:32.255+0000] {process_utils.py:190} INFO - Installing collected packages: libclang, flatbuffers, typing-extensions, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, querystring-parser, opt-einsum, numpy, keras, google-pasta, gast, entrypoints, astunparse, absl-py, h5py, botocore, s3transfer, google-auth-oauthlib, tensorboard, mlflow, boto3, tensorflow
[2024-11-18T21:33:32.521+0000] {process_utils.py:190} INFO -   Attempting uninstall: typing-extensions
[2024-11-18T21:33:32.522+0000] {process_utils.py:190} INFO -     Found existing installation: typing_extensions 4.9.0
[2024-11-18T21:33:32.523+0000] {process_utils.py:190} INFO -     Not uninstalling typing-extensions at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvbnvdq_j3
[2024-11-18T21:33:32.523+0000] {process_utils.py:190} INFO -     Can't uninstall 'typing_extensions'. No files were found to uninstall.
[2024-11-18T21:33:32.789+0000] {process_utils.py:190} INFO -   Attempting uninstall: numpy
[2024-11-18T21:33:32.790+0000] {process_utils.py:190} INFO -     Found existing installation: numpy 1.24.4
[2024-11-18T21:33:32.791+0000] {process_utils.py:190} INFO -     Not uninstalling numpy at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvbnvdq_j3
[2024-11-18T21:33:32.791+0000] {process_utils.py:190} INFO -     Can't uninstall 'numpy'. No files were found to uninstall.
[2024-11-18T21:33:34.574+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T21:33:34.575+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T21:33:34.575+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvbnvdq_j3
[2024-11-18T21:33:34.575+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T21:33:34.985+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T21:33:34.987+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T21:33:34.988+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvbnvdq_j3
[2024-11-18T21:33:34.990+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T21:33:35.009+0000] {process_utils.py:190} INFO -   Attempting uninstall: google-auth-oauthlib
[2024-11-18T21:33:35.010+0000] {process_utils.py:190} INFO -     Found existing installation: google-auth-oauthlib 1.2.0
[2024-11-18T21:33:35.011+0000] {process_utils.py:190} INFO -     Not uninstalling google-auth-oauthlib at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvbnvdq_j3
[2024-11-18T21:33:35.011+0000] {process_utils.py:190} INFO -     Can't uninstall 'google-auth-oauthlib'. No files were found to uninstall.
[2024-11-18T21:33:35.221+0000] {process_utils.py:190} INFO -   Attempting uninstall: mlflow
[2024-11-18T21:33:35.223+0000] {process_utils.py:190} INFO -     Found existing installation: mlflow 2.17.0
[2024-11-18T21:33:35.223+0000] {process_utils.py:190} INFO -     Not uninstalling mlflow at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvbnvdq_j3
[2024-11-18T21:33:35.223+0000] {process_utils.py:190} INFO -     Can't uninstall 'mlflow'. No files were found to uninstall.
[2024-11-18T21:33:35.787+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T21:33:35.787+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T21:33:35.788+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvbnvdq_j3
[2024-11-18T21:33:35.789+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T21:33:43.018+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T21:33:43.019+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T21:33:43.019+0000] {process_utils.py:190} INFO - azure-core 1.29.6 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:33:43.020+0000] {process_utils.py:190} INFO - azure-mgmt-keyvault 10.3.1 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:33:43.020+0000] {process_utils.py:190} INFO - azure-mgmt-network 27.0.0 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:33:43.020+0000] {process_utils.py:190} INFO - graphene 3.4 requires typing-extensions<5,>=4.7.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:33:43.021+0000] {process_utils.py:190} INFO - pydantic 2.5.3 requires typing-extensions>=4.6.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:33:43.021+0000] {process_utils.py:190} INFO - pydantic-core 2.14.6 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:33:43.022+0000] {process_utils.py:190} INFO - Successfully installed absl-py-2.1.0 astunparse-1.6.3 boto3-1.28.0 botocore-1.31.85 entrypoints-0.4 flatbuffers-24.3.25 gast-0.4.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 h5py-3.11.0 keras-2.13.1 libclang-18.1.1 mlflow-2.10.2 numpy-1.24.3 opt-einsum-3.4.0 querystring-parser-1.2.4 s3transfer-0.6.2 tensorboard-2.13.0 tensorboard-data-server-0.7.2 tensorflow-2.13.0 tensorflow-estimator-2.13.0 tensorflow-io-gcs-filesystem-0.34.0 typing-extensions-4.5.0
[2024-11-18T21:33:43.097+0000] {process_utils.py:190} INFO - 
[2024-11-18T21:33:43.098+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.3.1
[2024-11-18T21:33:43.098+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T21:33:43.290+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvbnvdq_j3/bin/python /tmp/venv-call8a10elgh/script.py /tmp/venv-call8a10elgh/script.in /tmp/venv-call8a10elgh/script.out /tmp/venv-call8a10elgh/string_args.txt /tmp/venv-call8a10elgh/termination.log
[2024-11-18T21:33:43.294+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T21:33:44.255+0000] {process_utils.py:190} INFO - 2024-11-18 21:33:44.255726: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-11-18T21:33:44.259+0000] {process_utils.py:190} INFO - 2024-11-18 21:33:44.256797: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T21:33:44.276+0000] {process_utils.py:190} INFO - 2024-11-18 21:33:44.276834: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T21:33:44.278+0000] {process_utils.py:190} INFO - 2024-11-18 21:33:44.277087: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-11-18T21:33:44.279+0000] {process_utils.py:190} INFO - To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-11-18T21:33:44.780+0000] {process_utils.py:190} INFO - 2024-11-18 21:33:44.780819: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-11-18T21:33:45.825+0000] {process_utils.py:190} INFO - Error loading data_info/song_embeddings.json from MinIO: Expecting value: line 1 column 1 (char 0)
[2024-11-18T21:33:45.825+0000] {process_utils.py:190} INFO - No existing embeddings found, initializing a new array.
[2024-11-18T21:33:45.826+0000] {process_utils.py:190} INFO - Epoch 1/10
[2024-11-18T21:33:46.711+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 3:26 - loss: 0.3462 55/575 [=>............................] - ETA: 0s - loss: 0.1550  118/575 [=====>........................] - ETA: 0s - loss: 0.1054197/575 [=========>....................] - ETA: 0s - loss: 0.0800282/575 [=============>................] - ETA: 0s - loss: 0.0656367/575 [==================>...........] - ETA: 0s - loss: 0.0561447/575 [======================>.......] - ETA: 0s - loss: 0.0500526/575 [==========================>...] - ETA: 0s - loss: 0.0456575/575 [==============================] - 1s 917us/step - loss: 0.0434 - val_loss: 0.0065
[2024-11-18T21:33:46.712+0000] {process_utils.py:190} INFO - Epoch 2/10
[2024-11-18T21:33:47.131+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0193 86/575 [===>..........................] - ETA: 0s - loss: 0.0173169/575 [=======>......................] - ETA: 0s - loss: 0.0170255/575 [============>.................] - ETA: 0s - loss: 0.0166341/575 [================>.............] - ETA: 0s - loss: 0.0162428/575 [=====================>........] - ETA: 0s - loss: 0.0159511/575 [=========================>....] - ETA: 0s - loss: 0.0155575/575 [==============================] - 0s 728us/step - loss: 0.0153 - val_loss: 0.0049
[2024-11-18T21:33:47.131+0000] {process_utils.py:190} INFO - Epoch 3/10
[2024-11-18T21:33:47.555+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0152 82/575 [===>..........................] - ETA: 0s - loss: 0.0128166/575 [=======>......................] - ETA: 0s - loss: 0.0126250/575 [============>.................] - ETA: 0s - loss: 0.0124334/575 [================>.............] - ETA: 0s - loss: 0.0123418/575 [====================>.........] - ETA: 0s - loss: 0.0121503/575 [=========================>....] - ETA: 0s - loss: 0.0119575/575 [==============================] - 0s 736us/step - loss: 0.0117 - val_loss: 0.0045
[2024-11-18T21:33:47.555+0000] {process_utils.py:190} INFO - Epoch 4/10
[2024-11-18T21:33:47.977+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0094 84/575 [===>..........................] - ETA: 0s - loss: 0.0104170/575 [=======>......................] - ETA: 0s - loss: 0.0103257/575 [============>.................] - ETA: 0s - loss: 0.0103339/575 [================>.............] - ETA: 0s - loss: 0.0102423/575 [=====================>........] - ETA: 0s - loss: 0.0101507/575 [=========================>....] - ETA: 0s - loss: 0.0099575/575 [==============================] - 0s 735us/step - loss: 0.0098 - val_loss: 0.0036
[2024-11-18T21:33:47.978+0000] {process_utils.py:190} INFO - Epoch 5/10
[2024-11-18T21:33:48.390+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0086 87/575 [===>..........................] - ETA: 0s - loss: 0.0088176/575 [========>.....................] - ETA: 0s - loss: 0.0087264/575 [============>.................] - ETA: 0s - loss: 0.0087349/575 [=================>............] - ETA: 0s - loss: 0.0087430/575 [=====================>........] - ETA: 0s - loss: 0.0086512/575 [=========================>....] - ETA: 0s - loss: 0.0085575/575 [==============================] - 0s 717us/step - loss: 0.0085 - val_loss: 0.0033
[2024-11-18T21:33:48.390+0000] {process_utils.py:190} INFO - Epoch 6/10
[2024-11-18T21:33:48.838+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0070 59/575 [==>...........................] - ETA: 0s - loss: 0.0076128/575 [=====>........................] - ETA: 0s - loss: 0.0076206/575 [=========>....................] - ETA: 0s - loss: 0.0077289/575 [==============>...............] - ETA: 0s - loss: 0.0078376/575 [==================>...........] - ETA: 0s - loss: 0.0078457/575 [======================>.......] - ETA: 0s - loss: 0.0078540/575 [===========================>..] - ETA: 0s - loss: 0.0077575/575 [==============================] - 0s 779us/step - loss: 0.0077 - val_loss: 0.0033
[2024-11-18T21:33:48.839+0000] {process_utils.py:190} INFO - Epoch 7/10
[2024-11-18T21:33:49.277+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0093 84/575 [===>..........................] - ETA: 0s - loss: 0.0075172/575 [=======>......................] - ETA: 0s - loss: 0.0076260/575 [============>.................] - ETA: 0s - loss: 0.0074345/575 [=================>............] - ETA: 0s - loss: 0.0074424/575 [=====================>........] - ETA: 0s - loss: 0.0073507/575 [=========================>....] - ETA: 0s - loss: 0.0073564/575 [============================>.] - ETA: 0s - loss: 0.0073575/575 [==============================] - 0s 762us/step - loss: 0.0073 - val_loss: 0.0024
[2024-11-18T21:33:49.278+0000] {process_utils.py:190} INFO - Epoch 8/10
[2024-11-18T21:33:49.722+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0060 84/575 [===>..........................] - ETA: 0s - loss: 0.0071163/575 [=======>......................] - ETA: 0s - loss: 0.0070241/575 [===========>..................] - ETA: 0s - loss: 0.0069321/575 [===============>..............] - ETA: 0s - loss: 0.0068400/575 [===================>..........] - ETA: 0s - loss: 0.0069479/575 [=======================>......] - ETA: 0s - loss: 0.0068558/575 [============================>.] - ETA: 0s - loss: 0.0068575/575 [==============================] - 0s 772us/step - loss: 0.0068 - val_loss: 0.0023
[2024-11-18T21:33:49.722+0000] {process_utils.py:190} INFO - Epoch 9/10
[2024-11-18T21:33:50.160+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0057 80/575 [===>..........................] - ETA: 0s - loss: 0.0067165/575 [=======>......................] - ETA: 0s - loss: 0.0067248/575 [===========>..................] - ETA: 0s - loss: 0.0066327/575 [================>.............] - ETA: 0s - loss: 0.0066407/575 [====================>.........] - ETA: 0s - loss: 0.0067488/575 [========================>.....] - ETA: 0s - loss: 0.0067554/575 [===========================>..] - ETA: 0s - loss: 0.0067575/575 [==============================] - 0s 761us/step - loss: 0.0067 - val_loss: 0.0022
[2024-11-18T21:33:50.160+0000] {process_utils.py:190} INFO - Epoch 10/10
[2024-11-18T21:33:50.597+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0071 82/575 [===>..........................] - ETA: 0s - loss: 0.0064162/575 [=======>......................] - ETA: 0s - loss: 0.0065241/575 [===========>..................] - ETA: 0s - loss: 0.0065318/575 [===============>..............] - ETA: 0s - loss: 0.0064401/575 [===================>..........] - ETA: 0s - loss: 0.0065484/575 [========================>.....] - ETA: 0s - loss: 0.0065569/575 [============================>.] - ETA: 0s - loss: 0.0065575/575 [==============================] - 0s 760us/step - loss: 0.0065 - val_loss: 0.0023
[2024-11-18T21:33:50.973+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 29s112/719 [===>..........................] - ETA: 0s 233/719 [========>.....................] - ETA: 0s345/719 [=============>................] - ETA: 0s456/719 [==================>...........] - ETA: 0s570/719 [======================>.......] - ETA: 0s685/719 [===========================>..] - ETA: 0s719/719 [==============================] - 0s 440us/step
[2024-11-18T21:33:51.551+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 7s108/719 [===>..........................] - ETA: 0s213/719 [=======>......................] - ETA: 0s326/719 [============>.................] - ETA: 0s435/719 [=================>............] - ETA: 0s549/719 [=====================>........] - ETA: 0s653/719 [==========================>...] - ETA: 0s719/719 [==============================] - 0s 461us/step
[2024-11-18T21:33:51.622+0000] {process_utils.py:190} INFO - 2024/11/18 21:33:51 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.
[2024-11-18T21:33:51.949+0000] {process_utils.py:190} INFO - [[34m2024-11-18T21:33:51.948+0000[0m] {[34mbuilder_impl.py:[0m804} INFO[0m - Assets written to: /tmp/tmpg88ctuh5/model/data/model/assets[0m
[2024-11-18T21:33:54.489+0000] {process_utils.py:190} INFO - /tmp/venvbnvdq_j3/lib/python3.8/site-packages/_distutils_hack/__init__.py:33 UserWarning: Setuptools is replacing distutils.
[2024-11-18T21:33:54.533+0000] {process_utils.py:190} INFO - [[34m2024-11-18T21:33:54.533+0000[0m] {[34mcredentials.py:[0m1124} INFO[0m - Found credentials in environment variables.[0m
[2024-11-18T21:33:54.662+0000] {process_utils.py:190} INFO - Registered model 'spotify_model_prod' already exists. Creating a new version of this model...
[2024-11-18T21:33:54.662+0000] {process_utils.py:190} INFO - 2024/11/18 21:33:54 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: spotify_model_prod, version 20
[2024-11-18T21:33:54.663+0000] {process_utils.py:190} INFO - Created version '20' of model 'spotify_model_prod'.
[2024-11-18T21:33:54.664+0000] {process_utils.py:190} INFO - /tmp/venvbnvdq_j3/lib/python3.8/site-packages/keras/src/engine/training.py:3000 UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
[2024-11-18T21:33:54.689+0000] {process_utils.py:190} INFO - Error saving data_info/song_embeddings.json to MinIO: [Errno 2] No such file or directory: 'data_info/song_embeddings.json'
[2024-11-18T21:33:55.619+0000] {python.py:201} INFO - Done. Returned value was: Challenger model trained and logged.
[2024-11-18T21:33:55.634+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=spotify_retrain_challenge_model_v3, task_id=train_challenger_model, execution_date=20241118T212758, start_date=20241118T213326, end_date=20241118T213355
[2024-11-18T21:33:55.646+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-11-18T21:33:55.657+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
