[2024-11-18T21:30:28.295+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T21:30:27.599810+00:00 [queued]>
[2024-11-18T21:30:28.299+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T21:30:27.599810+00:00 [queued]>
[2024-11-18T21:30:28.300+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-11-18T21:30:28.307+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): train_challenger_model> on 2024-11-18 21:30:27.599810+00:00
[2024-11-18T21:30:28.309+0000] {standard_task_runner.py:60} INFO - Started process 5976 to run task
[2024-11-18T21:30:28.311+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_retrain_challenge_model_v3', 'train_challenger_model', 'manual__2024-11-18T21:30:27.599810+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/retrain_music_model.py', '--cfg-path', '/tmp/tmpt86idivu']
[2024-11-18T21:30:28.312+0000] {standard_task_runner.py:88} INFO - Job 135: Subtask train_challenger_model
[2024-11-18T21:30:28.337+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T21:30:27.599810+00:00 [running]> on host 46787693bc19
[2024-11-18T21:30:28.376+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_retrain_challenge_model_v3' AIRFLOW_CTX_TASK_ID='train_challenger_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T21:30:27.599810+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T21:30:27.599810+00:00'
[2024-11-18T21:30:28.377+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venv224kcud0 --system-site-packages --python=python
[2024-11-18T21:30:28.381+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T21:30:28.719+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 121ms
[2024-11-18T21:30:28.719+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venv224kcud0, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T21:30:28.719+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T21:30:28.720+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-11-18T21:30:28.720+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T21:30:28.737+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv224kcud0/bin/pip install -r /tmp/venv224kcud0/requirements.txt
[2024-11-18T21:30:28.741+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T21:30:29.674+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venv224kcud0/requirements.txt (line 1))
[2024-11-18T21:30:29.676+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T21:30:29.713+0000] {process_utils.py:190} INFO - Collecting mlflow==2.10.2 (from -r /tmp/venv224kcud0/requirements.txt (line 2))
[2024-11-18T21:30:29.714+0000] {process_utils.py:190} INFO -   Using cached mlflow-2.10.2-py3-none-any.whl.metadata (13 kB)
[2024-11-18T21:30:29.715+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venv224kcud0/requirements.txt (line 3)) (2.0.3)
[2024-11-18T21:30:29.716+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn==1.3.2 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venv224kcud0/requirements.txt (line 4)) (1.3.2)
[2024-11-18T21:30:29.814+0000] {process_utils.py:190} INFO - Collecting tensorflow==2.13.0 (from -r /tmp/venv224kcud0/requirements.txt (line 5))
[2024-11-18T21:30:29.816+0000] {process_utils.py:190} INFO -   Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
[2024-11-18T21:30:30.203+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venv224kcud0/requirements.txt (line 1))
[2024-11-18T21:30:30.205+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T21:30:30.206+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venv224kcud0/requirements.txt (line 1)) (0.10.0)
[2024-11-18T21:30:30.233+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venv224kcud0/requirements.txt (line 1))
[2024-11-18T21:30:30.235+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T21:30:30.285+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (8.1.7)
[2024-11-18T21:30:30.285+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (3.1.0)
[2024-11-18T21:30:30.303+0000] {process_utils.py:190} INFO - Collecting entrypoints<1 (from mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2))
[2024-11-18T21:30:30.304+0000] {process_utils.py:190} INFO -   Using cached entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
[2024-11-18T21:30:30.305+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=2.1.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (3.1.43)
[2024-11-18T21:30:30.305+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (6.0.1)
[2024-11-18T21:30:30.306+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<5,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (4.25.2)
[2024-11-18T21:30:30.306+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz<2024 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T21:30:30.307+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (2.31.0)
[2024-11-18T21:30:30.307+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (23.2)
[2024-11-18T21:30:30.307+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (6.11.0)
[2024-11-18T21:30:30.308+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (0.4.4)
[2024-11-18T21:30:30.309+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (1.13.1)
[2024-11-18T21:30:30.309+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (7.0.0)
[2024-11-18T21:30:30.310+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (2.2.5)
[2024-11-18T21:30:30.310+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (1.24.4)
[2024-11-18T21:30:30.310+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (1.10.1)
[2024-11-18T21:30:30.325+0000] {process_utils.py:190} INFO - Collecting querystring-parser<2 (from mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2))
[2024-11-18T21:30:30.326+0000] {process_utils.py:190} INFO -   Using cached querystring_parser-1.2.4-py2.py3-none-any.whl.metadata (559 bytes)
[2024-11-18T21:30:30.327+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (1.4.51)
[2024-11-18T21:30:30.327+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow<16,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (14.0.2)
[2024-11-18T21:30:30.328+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (3.5.2)
[2024-11-18T21:30:30.328+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (3.7.5)
[2024-11-18T21:30:30.329+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<22 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (21.2.0)
[2024-11-18T21:30:30.330+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (3.1.3)
[2024-11-18T21:30:30.382+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venv224kcud0/requirements.txt (line 3)) (2.8.2)
[2024-11-18T21:30:30.383+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venv224kcud0/requirements.txt (line 3)) (2023.4)
[2024-11-18T21:30:30.405+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venv224kcud0/requirements.txt (line 4)) (1.4.2)
[2024-11-18T21:30:30.405+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venv224kcud0/requirements.txt (line 4)) (3.5.0)
[2024-11-18T21:30:30.438+0000] {process_utils.py:190} INFO - Collecting absl-py>=1.0.0 (from tensorflow==2.13.0->-r /tmp/venv224kcud0/requirements.txt (line 5))
[2024-11-18T21:30:30.439+0000] {process_utils.py:190} INFO -   Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
[2024-11-18T21:30:30.456+0000] {process_utils.py:190} INFO - Collecting astunparse>=1.6.0 (from tensorflow==2.13.0->-r /tmp/venv224kcud0/requirements.txt (line 5))
[2024-11-18T21:30:30.457+0000] {process_utils.py:190} INFO -   Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
[2024-11-18T21:30:30.475+0000] {process_utils.py:190} INFO - Collecting flatbuffers>=23.1.21 (from tensorflow==2.13.0->-r /tmp/venv224kcud0/requirements.txt (line 5))
[2024-11-18T21:30:30.477+0000] {process_utils.py:190} INFO -   Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
[2024-11-18T21:30:30.494+0000] {process_utils.py:190} INFO - Collecting gast<=0.4.0,>=0.2.1 (from tensorflow==2.13.0->-r /tmp/venv224kcud0/requirements.txt (line 5))
[2024-11-18T21:30:30.495+0000] {process_utils.py:190} INFO -   Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
[2024-11-18T21:30:30.513+0000] {process_utils.py:190} INFO - Collecting google-pasta>=0.1.1 (from tensorflow==2.13.0->-r /tmp/venv224kcud0/requirements.txt (line 5))
[2024-11-18T21:30:30.514+0000] {process_utils.py:190} INFO -   Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
[2024-11-18T21:30:30.514+0000] {process_utils.py:190} INFO - Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv224kcud0/requirements.txt (line 5)) (1.60.0)
[2024-11-18T21:30:30.555+0000] {process_utils.py:190} INFO - Collecting h5py>=2.9.0 (from tensorflow==2.13.0->-r /tmp/venv224kcud0/requirements.txt (line 5))
[2024-11-18T21:30:30.556+0000] {process_utils.py:190} INFO -   Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
[2024-11-18T21:30:30.584+0000] {process_utils.py:190} INFO - Collecting keras<2.14,>=2.13.1 (from tensorflow==2.13.0->-r /tmp/venv224kcud0/requirements.txt (line 5))
[2024-11-18T21:30:30.585+0000] {process_utils.py:190} INFO -   Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
[2024-11-18T21:30:30.605+0000] {process_utils.py:190} INFO - Collecting libclang>=13.0.0 (from tensorflow==2.13.0->-r /tmp/venv224kcud0/requirements.txt (line 5))
[2024-11-18T21:30:30.606+0000] {process_utils.py:190} INFO -   Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
[2024-11-18T21:30:30.757+0000] {process_utils.py:190} INFO - Collecting numpy<2 (from mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2))
[2024-11-18T21:30:30.759+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-11-18T21:30:30.775+0000] {process_utils.py:190} INFO - Collecting opt-einsum>=2.3.2 (from tensorflow==2.13.0->-r /tmp/venv224kcud0/requirements.txt (line 5))
[2024-11-18T21:30:30.777+0000] {process_utils.py:190} INFO -   Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
[2024-11-18T21:30:30.777+0000] {process_utils.py:190} INFO - Requirement already satisfied: setuptools in /tmp/venv224kcud0/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv224kcud0/requirements.txt (line 5)) (69.0.2)
[2024-11-18T21:30:30.778+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.12.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv224kcud0/requirements.txt (line 5)) (1.16.0)
[2024-11-18T21:30:30.801+0000] {process_utils.py:190} INFO - Collecting tensorboard<2.14,>=2.13 (from tensorflow==2.13.0->-r /tmp/venv224kcud0/requirements.txt (line 5))
[2024-11-18T21:30:30.802+0000] {process_utils.py:190} INFO -   Using cached tensorboard-2.13.0-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T21:30:30.822+0000] {process_utils.py:190} INFO - Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow==2.13.0->-r /tmp/venv224kcud0/requirements.txt (line 5))
[2024-11-18T21:30:30.824+0000] {process_utils.py:190} INFO -   Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
[2024-11-18T21:30:30.825+0000] {process_utils.py:190} INFO - Requirement already satisfied: termcolor>=1.1.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv224kcud0/requirements.txt (line 5)) (2.4.0)
[2024-11-18T21:30:30.849+0000] {process_utils.py:190} INFO - Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow==2.13.0->-r /tmp/venv224kcud0/requirements.txt (line 5))
[2024-11-18T21:30:30.851+0000] {process_utils.py:190} INFO -   Using cached typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
[2024-11-18T21:30:30.851+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt>=1.11.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv224kcud0/requirements.txt (line 5)) (1.16.0)
[2024-11-18T21:30:30.906+0000] {process_utils.py:190} INFO - Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow==2.13.0->-r /tmp/venv224kcud0/requirements.txt (line 5))
[2024-11-18T21:30:30.908+0000] {process_utils.py:190} INFO -   Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
[2024-11-18T21:30:30.915+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (1.3.0)
[2024-11-18T21:30:30.919+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (5.13.0)
[2024-11-18T21:30:30.922+0000] {process_utils.py:190} INFO - Requirement already satisfied: wheel<1.0,>=0.23.0 in /tmp/venv224kcud0/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow==2.13.0->-r /tmp/venv224kcud0/requirements.txt (line 5)) (0.42.0)
[2024-11-18T21:30:30.927+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venv224kcud0/requirements.txt (line 1)) (1.26.18)
[2024-11-18T21:30:30.941+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (2.2.3)
[2024-11-18T21:30:30.941+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (2.1.2)
[2024-11-18T21:30:30.958+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (4.0.11)
[2024-11-18T21:30:30.984+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (3.17.0)
[2024-11-18T21:30:30.988+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (2.1.3)
[2024-11-18T21:30:31.013+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (1.1.1)
[2024-11-18T21:30:31.013+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (0.12.1)
[2024-11-18T21:30:31.014+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (4.54.1)
[2024-11-18T21:30:31.014+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (1.4.7)
[2024-11-18T21:30:31.024+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (10.4.0)
[2024-11-18T21:30:31.024+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (3.1.1)
[2024-11-18T21:30:31.070+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (3.3.2)
[2024-11-18T21:30:31.071+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (3.6)
[2024-11-18T21:30:31.071+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (2023.11.17)
[2024-11-18T21:30:31.292+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (3.0.3)
[2024-11-18T21:30:31.311+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth<3,>=1.6.3 in /home/***/.local/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv224kcud0/requirements.txt (line 5)) (2.26.2)
[2024-11-18T21:30:31.331+0000] {process_utils.py:190} INFO - Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv224kcud0/requirements.txt (line 5))
[2024-11-18T21:30:31.332+0000] {process_utils.py:190} INFO -   Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
[2024-11-18T21:30:31.361+0000] {process_utils.py:190} INFO - Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv224kcud0/requirements.txt (line 5))
[2024-11-18T21:30:31.362+0000] {process_utils.py:190} INFO -   Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
[2024-11-18T21:30:31.505+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venv224kcud0/requirements.txt (line 2)) (5.0.1)
[2024-11-18T21:30:31.516+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv224kcud0/requirements.txt (line 5)) (5.3.2)
[2024-11-18T21:30:31.516+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv224kcud0/requirements.txt (line 5)) (0.3.0)
[2024-11-18T21:30:31.518+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv224kcud0/requirements.txt (line 5)) (4.9)
[2024-11-18T21:30:31.526+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv224kcud0/requirements.txt (line 5)) (1.3.1)
[2024-11-18T21:30:31.646+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv224kcud0/requirements.txt (line 5)) (0.5.1)
[2024-11-18T21:30:31.653+0000] {process_utils.py:190} INFO - Requirement already satisfied: oauthlib>=3.0.0 in /home/***/.local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv224kcud0/requirements.txt (line 5)) (3.2.2)
[2024-11-18T21:30:31.685+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T21:30:31.686+0000] {process_utils.py:190} INFO - Using cached mlflow-2.10.2-py3-none-any.whl (19.5 MB)
[2024-11-18T21:30:31.704+0000] {process_utils.py:190} INFO - Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.1 MB)
[2024-11-18T21:30:32.164+0000] {process_utils.py:190} INFO - Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
[2024-11-18T21:30:32.165+0000] {process_utils.py:190} INFO - Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
[2024-11-18T21:30:32.166+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T21:30:32.177+0000] {process_utils.py:190} INFO - Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
[2024-11-18T21:30:32.178+0000] {process_utils.py:190} INFO - Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
[2024-11-18T21:30:32.179+0000] {process_utils.py:190} INFO - Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
[2024-11-18T21:30:32.180+0000] {process_utils.py:190} INFO - Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
[2024-11-18T21:30:32.182+0000] {process_utils.py:190} INFO - Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
[2024-11-18T21:30:32.187+0000] {process_utils.py:190} INFO - Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)
[2024-11-18T21:30:32.190+0000] {process_utils.py:190} INFO - Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
[2024-11-18T21:30:32.214+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-11-18T21:30:32.230+0000] {process_utils.py:190} INFO - Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
[2024-11-18T21:30:32.232+0000] {process_utils.py:190} INFO - Using cached querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
[2024-11-18T21:30:32.233+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T21:30:32.234+0000] {process_utils.py:190} INFO - Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
[2024-11-18T21:30:32.240+0000] {process_utils.py:190} INFO - Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
[2024-11-18T21:30:32.242+0000] {process_utils.py:190} INFO - Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
[2024-11-18T21:30:32.245+0000] {process_utils.py:190} INFO - Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
[2024-11-18T21:30:32.246+0000] {process_utils.py:190} INFO - Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
[2024-11-18T21:30:32.247+0000] {process_utils.py:190} INFO - Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
[2024-11-18T21:30:34.371+0000] {process_utils.py:190} INFO - Installing collected packages: libclang, flatbuffers, typing-extensions, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, querystring-parser, opt-einsum, numpy, keras, google-pasta, gast, entrypoints, astunparse, absl-py, h5py, botocore, s3transfer, google-auth-oauthlib, tensorboard, mlflow, boto3, tensorflow
[2024-11-18T21:30:34.622+0000] {process_utils.py:190} INFO -   Attempting uninstall: typing-extensions
[2024-11-18T21:30:34.623+0000] {process_utils.py:190} INFO -     Found existing installation: typing_extensions 4.9.0
[2024-11-18T21:30:34.624+0000] {process_utils.py:190} INFO -     Not uninstalling typing-extensions at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv224kcud0
[2024-11-18T21:30:34.624+0000] {process_utils.py:190} INFO -     Can't uninstall 'typing_extensions'. No files were found to uninstall.
[2024-11-18T21:30:34.890+0000] {process_utils.py:190} INFO -   Attempting uninstall: numpy
[2024-11-18T21:30:34.892+0000] {process_utils.py:190} INFO -     Found existing installation: numpy 1.24.4
[2024-11-18T21:30:34.892+0000] {process_utils.py:190} INFO -     Not uninstalling numpy at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv224kcud0
[2024-11-18T21:30:34.893+0000] {process_utils.py:190} INFO -     Can't uninstall 'numpy'. No files were found to uninstall.
[2024-11-18T21:30:36.549+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T21:30:36.549+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T21:30:36.550+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv224kcud0
[2024-11-18T21:30:36.550+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T21:30:36.954+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T21:30:36.956+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T21:30:36.956+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv224kcud0
[2024-11-18T21:30:36.956+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T21:30:36.977+0000] {process_utils.py:190} INFO -   Attempting uninstall: google-auth-oauthlib
[2024-11-18T21:30:36.978+0000] {process_utils.py:190} INFO -     Found existing installation: google-auth-oauthlib 1.2.0
[2024-11-18T21:30:36.978+0000] {process_utils.py:190} INFO -     Not uninstalling google-auth-oauthlib at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv224kcud0
[2024-11-18T21:30:36.978+0000] {process_utils.py:190} INFO -     Can't uninstall 'google-auth-oauthlib'. No files were found to uninstall.
[2024-11-18T21:30:37.177+0000] {process_utils.py:190} INFO -   Attempting uninstall: mlflow
[2024-11-18T21:30:37.179+0000] {process_utils.py:190} INFO -     Found existing installation: mlflow 2.17.0
[2024-11-18T21:30:37.179+0000] {process_utils.py:190} INFO -     Not uninstalling mlflow at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv224kcud0
[2024-11-18T21:30:37.179+0000] {process_utils.py:190} INFO -     Can't uninstall 'mlflow'. No files were found to uninstall.
[2024-11-18T21:30:37.735+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T21:30:37.736+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T21:30:37.736+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv224kcud0
[2024-11-18T21:30:37.736+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T21:30:44.960+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T21:30:44.960+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T21:30:44.961+0000] {process_utils.py:190} INFO - azure-core 1.29.6 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:30:44.961+0000] {process_utils.py:190} INFO - azure-mgmt-keyvault 10.3.1 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:30:44.961+0000] {process_utils.py:190} INFO - azure-mgmt-network 27.0.0 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:30:44.961+0000] {process_utils.py:190} INFO - graphene 3.4 requires typing-extensions<5,>=4.7.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:30:44.961+0000] {process_utils.py:190} INFO - pydantic 2.5.3 requires typing-extensions>=4.6.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:30:44.962+0000] {process_utils.py:190} INFO - pydantic-core 2.14.6 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:30:44.962+0000] {process_utils.py:190} INFO - Successfully installed absl-py-2.1.0 astunparse-1.6.3 boto3-1.28.0 botocore-1.31.85 entrypoints-0.4 flatbuffers-24.3.25 gast-0.4.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 h5py-3.11.0 keras-2.13.1 libclang-18.1.1 mlflow-2.10.2 numpy-1.24.3 opt-einsum-3.4.0 querystring-parser-1.2.4 s3transfer-0.6.2 tensorboard-2.13.0 tensorboard-data-server-0.7.2 tensorflow-2.13.0 tensorflow-estimator-2.13.0 tensorflow-io-gcs-filesystem-0.34.0 typing-extensions-4.5.0
[2024-11-18T21:30:45.037+0000] {process_utils.py:190} INFO - 
[2024-11-18T21:30:45.037+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.3.1
[2024-11-18T21:30:45.038+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T21:30:45.223+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv224kcud0/bin/python /tmp/venv-callhct98swy/script.py /tmp/venv-callhct98swy/script.in /tmp/venv-callhct98swy/script.out /tmp/venv-callhct98swy/string_args.txt /tmp/venv-callhct98swy/termination.log
[2024-11-18T21:30:45.226+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T21:30:46.185+0000] {process_utils.py:190} INFO - 2024-11-18 21:30:46.185648: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-11-18T21:30:46.186+0000] {process_utils.py:190} INFO - 2024-11-18 21:30:46.186726: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T21:30:46.207+0000] {process_utils.py:190} INFO - 2024-11-18 21:30:46.207229: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T21:30:46.207+0000] {process_utils.py:190} INFO - 2024-11-18 21:30:46.207485: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-11-18T21:30:46.208+0000] {process_utils.py:190} INFO - To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-11-18T21:30:46.720+0000] {process_utils.py:190} INFO - 2024-11-18 21:30:46.720524: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-11-18T21:30:47.738+0000] {process_utils.py:190} INFO - Error loading data_info/song_embeddings.json from MinIO: Expecting value: line 1 column 1 (char 0)
[2024-11-18T21:30:47.739+0000] {process_utils.py:190} INFO - No existing embeddings found, initializing a new array.
[2024-11-18T21:30:47.739+0000] {process_utils.py:190} INFO - Epoch 1/10
[2024-11-18T21:30:48.627+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 3:27 - loss: 0.3123 51/575 [=>............................] - ETA: 0s - loss: 0.1545  110/575 [====>.........................] - ETA: 0s - loss: 0.1085197/575 [=========>....................] - ETA: 0s - loss: 0.0806282/575 [=============>................] - ETA: 0s - loss: 0.0665360/575 [=================>............] - ETA: 0s - loss: 0.0584443/575 [======================>.......] - ETA: 0s - loss: 0.0522524/575 [==========================>...] - ETA: 0s - loss: 0.0475575/575 [==============================] - 1s 918us/step - loss: 0.0452 - val_loss: 0.0067
[2024-11-18T21:30:48.627+0000] {process_utils.py:190} INFO - Epoch 2/10
[2024-11-18T21:30:49.050+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0182 82/575 [===>..........................] - ETA: 0s - loss: 0.0193163/575 [=======>......................] - ETA: 0s - loss: 0.0186248/575 [===========>..................] - ETA: 0s - loss: 0.0180333/575 [================>.............] - ETA: 0s - loss: 0.0175419/575 [====================>.........] - ETA: 0s - loss: 0.0170502/575 [=========================>....] - ETA: 0s - loss: 0.0166575/575 [==============================] - 0s 735us/step - loss: 0.0163 - val_loss: 0.0056
[2024-11-18T21:30:49.051+0000] {process_utils.py:190} INFO - Epoch 3/10
[2024-11-18T21:30:49.479+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0095 79/575 [===>..........................] - ETA: 0s - loss: 0.0142158/575 [=======>......................] - ETA: 0s - loss: 0.0137242/575 [===========>..................] - ETA: 0s - loss: 0.0135322/575 [===============>..............] - ETA: 0s - loss: 0.0133406/575 [====================>.........] - ETA: 0s - loss: 0.0130491/575 [========================>.....] - ETA: 0s - loss: 0.0127574/575 [============================>.] - ETA: 0s - loss: 0.0125575/575 [==============================] - 0s 746us/step - loss: 0.0125 - val_loss: 0.0044
[2024-11-18T21:30:49.480+0000] {process_utils.py:190} INFO - Epoch 4/10
[2024-11-18T21:30:49.901+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0108 88/575 [===>..........................] - ETA: 0s - loss: 0.0110175/575 [========>.....................] - ETA: 0s - loss: 0.0109254/575 [============>.................] - ETA: 0s - loss: 0.0107336/575 [================>.............] - ETA: 0s - loss: 0.0106420/575 [====================>.........] - ETA: 0s - loss: 0.0105501/575 [=========================>....] - ETA: 0s - loss: 0.0104575/575 [==============================] - 0s 733us/step - loss: 0.0103 - val_loss: 0.0036
[2024-11-18T21:30:49.901+0000] {process_utils.py:190} INFO - Epoch 5/10
[2024-11-18T21:30:50.326+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0111 82/575 [===>..........................] - ETA: 0s - loss: 0.0093152/575 [======>.......................] - ETA: 0s - loss: 0.0091238/575 [===========>..................] - ETA: 0s - loss: 0.0092325/575 [===============>..............] - ETA: 0s - loss: 0.0092409/575 [====================>.........] - ETA: 0s - loss: 0.0091493/575 [========================>.....] - ETA: 0s - loss: 0.0090575/575 [==============================] - 0s 739us/step - loss: 0.0090 - val_loss: 0.0031
[2024-11-18T21:30:50.326+0000] {process_utils.py:190} INFO - Epoch 6/10
[2024-11-18T21:30:50.735+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0055 87/575 [===>..........................] - ETA: 0s - loss: 0.0081175/575 [========>.....................] - ETA: 0s - loss: 0.0082263/575 [============>.................] - ETA: 0s - loss: 0.0082339/575 [================>.............] - ETA: 0s - loss: 0.0082432/575 [=====================>........] - ETA: 0s - loss: 0.0082522/575 [==========================>...] - ETA: 0s - loss: 0.0081575/575 [==============================] - 0s 710us/step - loss: 0.0081 - val_loss: 0.0028
[2024-11-18T21:30:50.735+0000] {process_utils.py:190} INFO - Epoch 7/10
[2024-11-18T21:30:51.148+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0070 84/575 [===>..........................] - ETA: 0s - loss: 0.0077166/575 [=======>......................] - ETA: 0s - loss: 0.0077254/575 [============>.................] - ETA: 0s - loss: 0.0077342/575 [================>.............] - ETA: 0s - loss: 0.0077426/575 [=====================>........] - ETA: 0s - loss: 0.0076512/575 [=========================>....] - ETA: 0s - loss: 0.0075575/575 [==============================] - 0s 719us/step - loss: 0.0075 - val_loss: 0.0027
[2024-11-18T21:30:51.149+0000] {process_utils.py:190} INFO - Epoch 8/10
[2024-11-18T21:30:51.554+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0077 88/575 [===>..........................] - ETA: 0s - loss: 0.0075177/575 [========>.....................] - ETA: 0s - loss: 0.0073264/575 [============>.................] - ETA: 0s - loss: 0.0073353/575 [=================>............] - ETA: 0s - loss: 0.0073438/575 [=====================>........] - ETA: 0s - loss: 0.0072525/575 [==========================>...] - ETA: 0s - loss: 0.0072575/575 [==============================] - 0s 705us/step - loss: 0.0072 - val_loss: 0.0029
[2024-11-18T21:30:51.554+0000] {process_utils.py:190} INFO - Epoch 9/10
[2024-11-18T21:30:51.967+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0079 87/575 [===>..........................] - ETA: 0s - loss: 0.0071174/575 [========>.....................] - ETA: 0s - loss: 0.0071256/575 [============>.................] - ETA: 0s - loss: 0.0070344/575 [================>.............] - ETA: 0s - loss: 0.0070428/575 [=====================>........] - ETA: 0s - loss: 0.0071509/575 [=========================>....] - ETA: 0s - loss: 0.0070575/575 [==============================] - 0s 717us/step - loss: 0.0070 - val_loss: 0.0026
[2024-11-18T21:30:51.967+0000] {process_utils.py:190} INFO - Epoch 10/10
[2024-11-18T21:30:52.386+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0063 85/575 [===>..........................] - ETA: 0s - loss: 0.0069172/575 [=======>......................] - ETA: 0s - loss: 0.0069246/575 [===========>..................] - ETA: 0s - loss: 0.0069327/575 [================>.............] - ETA: 0s - loss: 0.0069412/575 [====================>.........] - ETA: 0s - loss: 0.0069503/575 [=========================>....] - ETA: 0s - loss: 0.0069575/575 [==============================] - 0s 729us/step - loss: 0.0069 - val_loss: 0.0023
[2024-11-18T21:30:52.764+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 29s109/719 [===>..........................] - ETA: 0s 222/719 [========>.....................] - ETA: 0s335/719 [============>.................] - ETA: 0s453/719 [=================>............] - ETA: 0s569/719 [======================>.......] - ETA: 0s684/719 [===========================>..] - ETA: 0s719/719 [==============================] - 0s 442us/step
[2024-11-18T21:30:53.293+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 7s105/719 [===>..........................] - ETA: 0s215/719 [=======>......................] - ETA: 0s327/719 [============>.................] - ETA: 0s441/719 [=================>............] - ETA: 0s555/719 [======================>.......] - ETA: 0s669/719 [==========================>...] - ETA: 0s719/719 [==============================] - 0s 448us/step
[2024-11-18T21:30:53.383+0000] {process_utils.py:190} INFO - 2024/11/18 21:30:53 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.
[2024-11-18T21:30:53.698+0000] {process_utils.py:190} INFO - [[34m2024-11-18T21:30:53.698+0000[0m] {[34mbuilder_impl.py:[0m804} INFO[0m - Assets written to: /tmp/tmp4tu0pys3/model/data/model/assets[0m
[2024-11-18T21:30:56.135+0000] {process_utils.py:190} INFO - /tmp/venv224kcud0/lib/python3.8/site-packages/_distutils_hack/__init__.py:33 UserWarning: Setuptools is replacing distutils.
[2024-11-18T21:30:56.152+0000] {process_utils.py:190} INFO - [[34m2024-11-18T21:30:56.152+0000[0m] {[34mcredentials.py:[0m1124} INFO[0m - Found credentials in environment variables.[0m
[2024-11-18T21:30:56.266+0000] {process_utils.py:190} INFO - Registered model 'spotify_model_prod' already exists. Creating a new version of this model...
[2024-11-18T21:30:56.267+0000] {process_utils.py:190} INFO - 2024/11/18 21:30:56 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: spotify_model_prod, version 18
[2024-11-18T21:30:56.267+0000] {process_utils.py:190} INFO - Created version '18' of model 'spotify_model_prod'.
[2024-11-18T21:30:56.267+0000] {process_utils.py:190} INFO - /tmp/venv224kcud0/lib/python3.8/site-packages/keras/src/engine/training.py:3000 UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
[2024-11-18T21:30:56.294+0000] {process_utils.py:190} INFO - Error saving data_info/song_embeddings.json to MinIO: [Errno 2] No such file or directory: 'data_info/song_embeddings.json'
[2024-11-18T21:30:57.178+0000] {python.py:201} INFO - Done. Returned value was: Challenger model trained and logged.
[2024-11-18T21:30:57.217+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=spotify_retrain_challenge_model_v3, task_id=train_challenger_model, execution_date=20241118T213027, start_date=20241118T213028, end_date=20241118T213057
[2024-11-18T21:30:57.265+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-11-18T21:30:57.284+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
