[2024-11-18T21:32:11.287+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T21:26:48.856733+00:00 [queued]>
[2024-11-18T21:32:11.292+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T21:26:48.856733+00:00 [queued]>
[2024-11-18T21:32:11.292+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-11-18T21:32:11.299+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): train_challenger_model> on 2024-11-18 21:26:48.856733+00:00
[2024-11-18T21:32:11.302+0000] {standard_task_runner.py:60} INFO - Started process 6958 to run task
[2024-11-18T21:32:11.303+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_retrain_challenge_model_v3', 'train_challenger_model', 'manual__2024-11-18T21:26:48.856733+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/retrain_music_model.py', '--cfg-path', '/tmp/tmpx_srhqju']
[2024-11-18T21:32:11.304+0000] {standard_task_runner.py:88} INFO - Job 137: Subtask train_challenger_model
[2024-11-18T21:32:11.329+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T21:26:48.856733+00:00 [running]> on host 46787693bc19
[2024-11-18T21:32:11.371+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_retrain_challenge_model_v3' AIRFLOW_CTX_TASK_ID='train_challenger_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T21:26:48.856733+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T21:26:48.856733+00:00'
[2024-11-18T21:32:11.372+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvid5tekn7 --system-site-packages --python=python
[2024-11-18T21:32:11.376+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T21:32:11.708+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 118ms
[2024-11-18T21:32:11.708+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvid5tekn7, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T21:32:11.709+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T21:32:11.709+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-11-18T21:32:11.709+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T21:32:11.726+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvid5tekn7/bin/pip install -r /tmp/venvid5tekn7/requirements.txt
[2024-11-18T21:32:11.731+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T21:32:12.675+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venvid5tekn7/requirements.txt (line 1))
[2024-11-18T21:32:12.678+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T21:32:12.766+0000] {process_utils.py:190} INFO - Collecting mlflow==2.10.2 (from -r /tmp/venvid5tekn7/requirements.txt (line 2))
[2024-11-18T21:32:12.767+0000] {process_utils.py:190} INFO -   Using cached mlflow-2.10.2-py3-none-any.whl.metadata (13 kB)
[2024-11-18T21:32:12.769+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvid5tekn7/requirements.txt (line 3)) (2.0.3)
[2024-11-18T21:32:12.769+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn==1.3.2 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvid5tekn7/requirements.txt (line 4)) (1.3.2)
[2024-11-18T21:32:12.871+0000] {process_utils.py:190} INFO - Collecting tensorflow==2.13.0 (from -r /tmp/venvid5tekn7/requirements.txt (line 5))
[2024-11-18T21:32:12.873+0000] {process_utils.py:190} INFO -   Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
[2024-11-18T21:32:13.291+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venvid5tekn7/requirements.txt (line 1))
[2024-11-18T21:32:13.292+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T21:32:13.293+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venvid5tekn7/requirements.txt (line 1)) (0.10.0)
[2024-11-18T21:32:13.315+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venvid5tekn7/requirements.txt (line 1))
[2024-11-18T21:32:13.316+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T21:32:13.365+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (8.1.7)
[2024-11-18T21:32:13.366+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (3.1.0)
[2024-11-18T21:32:13.383+0000] {process_utils.py:190} INFO - Collecting entrypoints<1 (from mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2))
[2024-11-18T21:32:13.384+0000] {process_utils.py:190} INFO -   Using cached entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
[2024-11-18T21:32:13.385+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=2.1.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (3.1.43)
[2024-11-18T21:32:13.385+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (6.0.1)
[2024-11-18T21:32:13.386+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<5,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (4.25.2)
[2024-11-18T21:32:13.386+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz<2024 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T21:32:13.387+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (2.31.0)
[2024-11-18T21:32:13.387+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (23.2)
[2024-11-18T21:32:13.388+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (6.11.0)
[2024-11-18T21:32:13.389+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (0.4.4)
[2024-11-18T21:32:13.389+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (1.13.1)
[2024-11-18T21:32:13.390+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (7.0.0)
[2024-11-18T21:32:13.391+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (2.2.5)
[2024-11-18T21:32:13.391+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (1.24.4)
[2024-11-18T21:32:13.392+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (1.10.1)
[2024-11-18T21:32:13.404+0000] {process_utils.py:190} INFO - Collecting querystring-parser<2 (from mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2))
[2024-11-18T21:32:13.406+0000] {process_utils.py:190} INFO -   Using cached querystring_parser-1.2.4-py2.py3-none-any.whl.metadata (559 bytes)
[2024-11-18T21:32:13.406+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (1.4.51)
[2024-11-18T21:32:13.407+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow<16,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (14.0.2)
[2024-11-18T21:32:13.407+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (3.5.2)
[2024-11-18T21:32:13.408+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (3.7.5)
[2024-11-18T21:32:13.408+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<22 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (21.2.0)
[2024-11-18T21:32:13.409+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (3.1.3)
[2024-11-18T21:32:13.461+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvid5tekn7/requirements.txt (line 3)) (2.8.2)
[2024-11-18T21:32:13.461+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvid5tekn7/requirements.txt (line 3)) (2023.4)
[2024-11-18T21:32:13.481+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvid5tekn7/requirements.txt (line 4)) (1.4.2)
[2024-11-18T21:32:13.482+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvid5tekn7/requirements.txt (line 4)) (3.5.0)
[2024-11-18T21:32:13.515+0000] {process_utils.py:190} INFO - Collecting absl-py>=1.0.0 (from tensorflow==2.13.0->-r /tmp/venvid5tekn7/requirements.txt (line 5))
[2024-11-18T21:32:13.517+0000] {process_utils.py:190} INFO -   Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
[2024-11-18T21:32:13.532+0000] {process_utils.py:190} INFO - Collecting astunparse>=1.6.0 (from tensorflow==2.13.0->-r /tmp/venvid5tekn7/requirements.txt (line 5))
[2024-11-18T21:32:13.533+0000] {process_utils.py:190} INFO -   Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
[2024-11-18T21:32:13.550+0000] {process_utils.py:190} INFO - Collecting flatbuffers>=23.1.21 (from tensorflow==2.13.0->-r /tmp/venvid5tekn7/requirements.txt (line 5))
[2024-11-18T21:32:13.551+0000] {process_utils.py:190} INFO -   Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
[2024-11-18T21:32:13.569+0000] {process_utils.py:190} INFO - Collecting gast<=0.4.0,>=0.2.1 (from tensorflow==2.13.0->-r /tmp/venvid5tekn7/requirements.txt (line 5))
[2024-11-18T21:32:13.571+0000] {process_utils.py:190} INFO -   Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
[2024-11-18T21:32:13.588+0000] {process_utils.py:190} INFO - Collecting google-pasta>=0.1.1 (from tensorflow==2.13.0->-r /tmp/venvid5tekn7/requirements.txt (line 5))
[2024-11-18T21:32:13.589+0000] {process_utils.py:190} INFO -   Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
[2024-11-18T21:32:13.590+0000] {process_utils.py:190} INFO - Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvid5tekn7/requirements.txt (line 5)) (1.60.0)
[2024-11-18T21:32:13.629+0000] {process_utils.py:190} INFO - Collecting h5py>=2.9.0 (from tensorflow==2.13.0->-r /tmp/venvid5tekn7/requirements.txt (line 5))
[2024-11-18T21:32:13.630+0000] {process_utils.py:190} INFO -   Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
[2024-11-18T21:32:13.659+0000] {process_utils.py:190} INFO - Collecting keras<2.14,>=2.13.1 (from tensorflow==2.13.0->-r /tmp/venvid5tekn7/requirements.txt (line 5))
[2024-11-18T21:32:13.660+0000] {process_utils.py:190} INFO -   Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
[2024-11-18T21:32:13.682+0000] {process_utils.py:190} INFO - Collecting libclang>=13.0.0 (from tensorflow==2.13.0->-r /tmp/venvid5tekn7/requirements.txt (line 5))
[2024-11-18T21:32:13.683+0000] {process_utils.py:190} INFO -   Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
[2024-11-18T21:32:13.830+0000] {process_utils.py:190} INFO - Collecting numpy<2 (from mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2))
[2024-11-18T21:32:13.833+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-11-18T21:32:13.847+0000] {process_utils.py:190} INFO - Collecting opt-einsum>=2.3.2 (from tensorflow==2.13.0->-r /tmp/venvid5tekn7/requirements.txt (line 5))
[2024-11-18T21:32:13.848+0000] {process_utils.py:190} INFO -   Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
[2024-11-18T21:32:13.849+0000] {process_utils.py:190} INFO - Requirement already satisfied: setuptools in /tmp/venvid5tekn7/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvid5tekn7/requirements.txt (line 5)) (69.0.2)
[2024-11-18T21:32:13.850+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.12.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvid5tekn7/requirements.txt (line 5)) (1.16.0)
[2024-11-18T21:32:13.874+0000] {process_utils.py:190} INFO - Collecting tensorboard<2.14,>=2.13 (from tensorflow==2.13.0->-r /tmp/venvid5tekn7/requirements.txt (line 5))
[2024-11-18T21:32:13.875+0000] {process_utils.py:190} INFO -   Using cached tensorboard-2.13.0-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T21:32:13.892+0000] {process_utils.py:190} INFO - Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow==2.13.0->-r /tmp/venvid5tekn7/requirements.txt (line 5))
[2024-11-18T21:32:13.894+0000] {process_utils.py:190} INFO -   Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
[2024-11-18T21:32:13.894+0000] {process_utils.py:190} INFO - Requirement already satisfied: termcolor>=1.1.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvid5tekn7/requirements.txt (line 5)) (2.4.0)
[2024-11-18T21:32:13.917+0000] {process_utils.py:190} INFO - Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow==2.13.0->-r /tmp/venvid5tekn7/requirements.txt (line 5))
[2024-11-18T21:32:13.919+0000] {process_utils.py:190} INFO -   Using cached typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
[2024-11-18T21:32:13.919+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt>=1.11.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvid5tekn7/requirements.txt (line 5)) (1.16.0)
[2024-11-18T21:32:13.978+0000] {process_utils.py:190} INFO - Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow==2.13.0->-r /tmp/venvid5tekn7/requirements.txt (line 5))
[2024-11-18T21:32:13.980+0000] {process_utils.py:190} INFO -   Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
[2024-11-18T21:32:13.988+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (1.3.0)
[2024-11-18T21:32:13.991+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (5.13.0)
[2024-11-18T21:32:13.994+0000] {process_utils.py:190} INFO - Requirement already satisfied: wheel<1.0,>=0.23.0 in /tmp/venvid5tekn7/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow==2.13.0->-r /tmp/venvid5tekn7/requirements.txt (line 5)) (0.42.0)
[2024-11-18T21:32:14.000+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venvid5tekn7/requirements.txt (line 1)) (1.26.18)
[2024-11-18T21:32:14.014+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (2.2.3)
[2024-11-18T21:32:14.014+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (2.1.2)
[2024-11-18T21:32:14.031+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (4.0.11)
[2024-11-18T21:32:14.056+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (3.17.0)
[2024-11-18T21:32:14.059+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (2.1.3)
[2024-11-18T21:32:14.082+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (1.1.1)
[2024-11-18T21:32:14.083+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (0.12.1)
[2024-11-18T21:32:14.083+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (4.54.1)
[2024-11-18T21:32:14.084+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (1.4.7)
[2024-11-18T21:32:14.093+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (10.4.0)
[2024-11-18T21:32:14.093+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (3.1.1)
[2024-11-18T21:32:14.136+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (3.3.2)
[2024-11-18T21:32:14.136+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (3.6)
[2024-11-18T21:32:14.137+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (2023.11.17)
[2024-11-18T21:32:14.382+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (3.0.3)
[2024-11-18T21:32:14.401+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth<3,>=1.6.3 in /home/***/.local/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvid5tekn7/requirements.txt (line 5)) (2.26.2)
[2024-11-18T21:32:14.422+0000] {process_utils.py:190} INFO - Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvid5tekn7/requirements.txt (line 5))
[2024-11-18T21:32:14.424+0000] {process_utils.py:190} INFO -   Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
[2024-11-18T21:32:14.450+0000] {process_utils.py:190} INFO - Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvid5tekn7/requirements.txt (line 5))
[2024-11-18T21:32:14.452+0000] {process_utils.py:190} INFO -   Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
[2024-11-18T21:32:14.586+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvid5tekn7/requirements.txt (line 2)) (5.0.1)
[2024-11-18T21:32:14.597+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvid5tekn7/requirements.txt (line 5)) (5.3.2)
[2024-11-18T21:32:14.598+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvid5tekn7/requirements.txt (line 5)) (0.3.0)
[2024-11-18T21:32:14.603+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvid5tekn7/requirements.txt (line 5)) (4.9)
[2024-11-18T21:32:14.604+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvid5tekn7/requirements.txt (line 5)) (1.3.1)
[2024-11-18T21:32:14.732+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvid5tekn7/requirements.txt (line 5)) (0.5.1)
[2024-11-18T21:32:14.739+0000] {process_utils.py:190} INFO - Requirement already satisfied: oauthlib>=3.0.0 in /home/***/.local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvid5tekn7/requirements.txt (line 5)) (3.2.2)
[2024-11-18T21:32:14.771+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T21:32:14.773+0000] {process_utils.py:190} INFO - Using cached mlflow-2.10.2-py3-none-any.whl (19.5 MB)
[2024-11-18T21:32:14.793+0000] {process_utils.py:190} INFO - Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.1 MB)
[2024-11-18T21:32:15.281+0000] {process_utils.py:190} INFO - Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
[2024-11-18T21:32:15.283+0000] {process_utils.py:190} INFO - Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
[2024-11-18T21:32:15.284+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T21:32:15.295+0000] {process_utils.py:190} INFO - Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
[2024-11-18T21:32:15.297+0000] {process_utils.py:190} INFO - Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
[2024-11-18T21:32:15.298+0000] {process_utils.py:190} INFO - Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
[2024-11-18T21:32:15.299+0000] {process_utils.py:190} INFO - Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
[2024-11-18T21:32:15.300+0000] {process_utils.py:190} INFO - Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
[2024-11-18T21:32:15.306+0000] {process_utils.py:190} INFO - Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)
[2024-11-18T21:32:15.308+0000] {process_utils.py:190} INFO - Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
[2024-11-18T21:32:15.333+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-11-18T21:32:15.351+0000] {process_utils.py:190} INFO - Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
[2024-11-18T21:32:15.352+0000] {process_utils.py:190} INFO - Using cached querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
[2024-11-18T21:32:15.353+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T21:32:15.354+0000] {process_utils.py:190} INFO - Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
[2024-11-18T21:32:15.360+0000] {process_utils.py:190} INFO - Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
[2024-11-18T21:32:15.363+0000] {process_utils.py:190} INFO - Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
[2024-11-18T21:32:15.365+0000] {process_utils.py:190} INFO - Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
[2024-11-18T21:32:15.366+0000] {process_utils.py:190} INFO - Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
[2024-11-18T21:32:15.369+0000] {process_utils.py:190} INFO - Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
[2024-11-18T21:32:17.433+0000] {process_utils.py:190} INFO - Installing collected packages: libclang, flatbuffers, typing-extensions, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, querystring-parser, opt-einsum, numpy, keras, google-pasta, gast, entrypoints, astunparse, absl-py, h5py, botocore, s3transfer, google-auth-oauthlib, tensorboard, mlflow, boto3, tensorflow
[2024-11-18T21:32:17.698+0000] {process_utils.py:190} INFO -   Attempting uninstall: typing-extensions
[2024-11-18T21:32:17.700+0000] {process_utils.py:190} INFO -     Found existing installation: typing_extensions 4.9.0
[2024-11-18T21:32:17.700+0000] {process_utils.py:190} INFO -     Not uninstalling typing-extensions at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvid5tekn7
[2024-11-18T21:32:17.701+0000] {process_utils.py:190} INFO -     Can't uninstall 'typing_extensions'. No files were found to uninstall.
[2024-11-18T21:32:17.965+0000] {process_utils.py:190} INFO -   Attempting uninstall: numpy
[2024-11-18T21:32:17.967+0000] {process_utils.py:190} INFO -     Found existing installation: numpy 1.24.4
[2024-11-18T21:32:17.967+0000] {process_utils.py:190} INFO -     Not uninstalling numpy at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvid5tekn7
[2024-11-18T21:32:17.967+0000] {process_utils.py:190} INFO -     Can't uninstall 'numpy'. No files were found to uninstall.
[2024-11-18T21:32:19.660+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T21:32:19.661+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T21:32:19.661+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvid5tekn7
[2024-11-18T21:32:19.661+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T21:32:20.061+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T21:32:20.062+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T21:32:20.062+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvid5tekn7
[2024-11-18T21:32:20.063+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T21:32:20.086+0000] {process_utils.py:190} INFO -   Attempting uninstall: google-auth-oauthlib
[2024-11-18T21:32:20.087+0000] {process_utils.py:190} INFO -     Found existing installation: google-auth-oauthlib 1.2.0
[2024-11-18T21:32:20.087+0000] {process_utils.py:190} INFO -     Not uninstalling google-auth-oauthlib at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvid5tekn7
[2024-11-18T21:32:20.087+0000] {process_utils.py:190} INFO -     Can't uninstall 'google-auth-oauthlib'. No files were found to uninstall.
[2024-11-18T21:32:20.290+0000] {process_utils.py:190} INFO -   Attempting uninstall: mlflow
[2024-11-18T21:32:20.292+0000] {process_utils.py:190} INFO -     Found existing installation: mlflow 2.17.0
[2024-11-18T21:32:20.293+0000] {process_utils.py:190} INFO -     Not uninstalling mlflow at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvid5tekn7
[2024-11-18T21:32:20.293+0000] {process_utils.py:190} INFO -     Can't uninstall 'mlflow'. No files were found to uninstall.
[2024-11-18T21:32:20.877+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T21:32:20.877+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T21:32:20.878+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvid5tekn7
[2024-11-18T21:32:20.878+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T21:32:28.165+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T21:32:28.165+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T21:32:28.166+0000] {process_utils.py:190} INFO - azure-core 1.29.6 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:32:28.166+0000] {process_utils.py:190} INFO - azure-mgmt-keyvault 10.3.1 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:32:28.166+0000] {process_utils.py:190} INFO - azure-mgmt-network 27.0.0 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:32:28.166+0000] {process_utils.py:190} INFO - graphene 3.4 requires typing-extensions<5,>=4.7.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:32:28.166+0000] {process_utils.py:190} INFO - pydantic 2.5.3 requires typing-extensions>=4.6.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:32:28.166+0000] {process_utils.py:190} INFO - pydantic-core 2.14.6 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T21:32:28.167+0000] {process_utils.py:190} INFO - Successfully installed absl-py-2.1.0 astunparse-1.6.3 boto3-1.28.0 botocore-1.31.85 entrypoints-0.4 flatbuffers-24.3.25 gast-0.4.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 h5py-3.11.0 keras-2.13.1 libclang-18.1.1 mlflow-2.10.2 numpy-1.24.3 opt-einsum-3.4.0 querystring-parser-1.2.4 s3transfer-0.6.2 tensorboard-2.13.0 tensorboard-data-server-0.7.2 tensorflow-2.13.0 tensorflow-estimator-2.13.0 tensorflow-io-gcs-filesystem-0.34.0 typing-extensions-4.5.0
[2024-11-18T21:32:28.241+0000] {process_utils.py:190} INFO - 
[2024-11-18T21:32:28.242+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.3.1
[2024-11-18T21:32:28.242+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T21:32:28.443+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvid5tekn7/bin/python /tmp/venv-calli9716914/script.py /tmp/venv-calli9716914/script.in /tmp/venv-calli9716914/script.out /tmp/venv-calli9716914/string_args.txt /tmp/venv-calli9716914/termination.log
[2024-11-18T21:32:28.447+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T21:32:29.416+0000] {process_utils.py:190} INFO - 2024-11-18 21:32:29.415903: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-11-18T21:32:29.417+0000] {process_utils.py:190} INFO - 2024-11-18 21:32:29.417008: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T21:32:29.438+0000] {process_utils.py:190} INFO - 2024-11-18 21:32:29.438027: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T21:32:29.438+0000] {process_utils.py:190} INFO - 2024-11-18 21:32:29.438294: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-11-18T21:32:29.438+0000] {process_utils.py:190} INFO - To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-11-18T21:32:29.945+0000] {process_utils.py:190} INFO - 2024-11-18 21:32:29.945470: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-11-18T21:32:30.964+0000] {process_utils.py:190} INFO - Error loading data_info/song_embeddings.json from MinIO: Expecting value: line 1 column 1 (char 0)
[2024-11-18T21:32:30.964+0000] {process_utils.py:190} INFO - No existing embeddings found, initializing a new array.
[2024-11-18T21:32:30.965+0000] {process_utils.py:190} INFO - Epoch 1/10
[2024-11-18T21:32:31.862+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 3:25 - loss: 0.4456 51/575 [=>............................] - ETA: 0s - loss: 0.1521  110/575 [====>.........................] - ETA: 0s - loss: 0.1048188/575 [========>.....................] - ETA: 0s - loss: 0.0807266/575 [============>.................] - ETA: 0s - loss: 0.0678344/575 [================>.............] - ETA: 0s - loss: 0.0595424/575 [=====================>........] - ETA: 0s - loss: 0.0532505/575 [=========================>....] - ETA: 0s - loss: 0.0486575/575 [==============================] - 1s 939us/step - loss: 0.0453 - val_loss: 0.0088
[2024-11-18T21:32:31.862+0000] {process_utils.py:190} INFO - Epoch 2/10
[2024-11-18T21:32:32.292+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0211 84/575 [===>..........................] - ETA: 0s - loss: 0.0206166/575 [=======>......................] - ETA: 0s - loss: 0.0194248/575 [===========>..................] - ETA: 0s - loss: 0.0186330/575 [================>.............] - ETA: 0s - loss: 0.0179415/575 [====================>.........] - ETA: 0s - loss: 0.0174498/575 [========================>.....] - ETA: 0s - loss: 0.0169575/575 [==============================] - 0s 747us/step - loss: 0.0165 - val_loss: 0.0052
[2024-11-18T21:32:32.292+0000] {process_utils.py:190} INFO - Epoch 3/10
[2024-11-18T21:32:32.732+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0120 84/575 [===>..........................] - ETA: 0s - loss: 0.0130162/575 [=======>......................] - ETA: 0s - loss: 0.0127239/575 [===========>..................] - ETA: 0s - loss: 0.0126317/575 [===============>..............] - ETA: 0s - loss: 0.0124398/575 [===================>..........] - ETA: 0s - loss: 0.0122481/575 [========================>.....] - ETA: 0s - loss: 0.0119562/575 [============================>.] - ETA: 0s - loss: 0.0117575/575 [==============================] - 0s 765us/step - loss: 0.0117 - val_loss: 0.0039
[2024-11-18T21:32:32.733+0000] {process_utils.py:190} INFO - Epoch 4/10
[2024-11-18T21:32:33.175+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0085 81/575 [===>..........................] - ETA: 0s - loss: 0.0100162/575 [=======>......................] - ETA: 0s - loss: 0.0099242/575 [===========>..................] - ETA: 0s - loss: 0.0099324/575 [===============>..............] - ETA: 0s - loss: 0.0098395/575 [===================>..........] - ETA: 0s - loss: 0.0098478/575 [=======================>......] - ETA: 0s - loss: 0.0096560/575 [============================>.] - ETA: 0s - loss: 0.0095575/575 [==============================] - 0s 769us/step - loss: 0.0095 - val_loss: 0.0041
[2024-11-18T21:32:33.175+0000] {process_utils.py:190} INFO - Epoch 5/10
[2024-11-18T21:32:33.609+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0089 81/575 [===>..........................] - ETA: 0s - loss: 0.0092164/575 [=======>......................] - ETA: 0s - loss: 0.0088247/575 [===========>..................] - ETA: 0s - loss: 0.0087325/575 [===============>..............] - ETA: 0s - loss: 0.0086406/575 [====================>.........] - ETA: 0s - loss: 0.0086485/575 [========================>.....] - ETA: 0s - loss: 0.0086567/575 [============================>.] - ETA: 0s - loss: 0.0085575/575 [==============================] - 0s 754us/step - loss: 0.0085 - val_loss: 0.0034
[2024-11-18T21:32:33.609+0000] {process_utils.py:190} INFO - Epoch 6/10
[2024-11-18T21:32:34.044+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0066 84/575 [===>..........................] - ETA: 0s - loss: 0.0083161/575 [=======>......................] - ETA: 0s - loss: 0.0083249/575 [===========>..................] - ETA: 0s - loss: 0.0082333/575 [================>.............] - ETA: 0s - loss: 0.0082411/575 [====================>.........] - ETA: 0s - loss: 0.0081489/575 [========================>.....] - ETA: 0s - loss: 0.0080571/575 [============================>.] - ETA: 0s - loss: 0.0080575/575 [==============================] - 0s 756us/step - loss: 0.0080 - val_loss: 0.0029
[2024-11-18T21:32:34.044+0000] {process_utils.py:190} INFO - Epoch 7/10
[2024-11-18T21:32:34.480+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0079 82/575 [===>..........................] - ETA: 0s - loss: 0.0075164/575 [=======>......................] - ETA: 0s - loss: 0.0076246/575 [===========>..................] - ETA: 0s - loss: 0.0076330/575 [================>.............] - ETA: 0s - loss: 0.0075406/575 [====================>.........] - ETA: 0s - loss: 0.0075487/575 [========================>.....] - ETA: 0s - loss: 0.0075566/575 [============================>.] - ETA: 0s - loss: 0.0074575/575 [==============================] - 0s 757us/step - loss: 0.0074 - val_loss: 0.0026
[2024-11-18T21:32:34.480+0000] {process_utils.py:190} INFO - Epoch 8/10
[2024-11-18T21:32:34.921+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0066 83/575 [===>..........................] - ETA: 0s - loss: 0.0070165/575 [=======>......................] - ETA: 0s - loss: 0.0070246/575 [===========>..................] - ETA: 0s - loss: 0.0071328/575 [================>.............] - ETA: 0s - loss: 0.0070409/575 [====================>.........] - ETA: 0s - loss: 0.0071489/575 [========================>.....] - ETA: 0s - loss: 0.0070564/575 [============================>.] - ETA: 0s - loss: 0.0070575/575 [==============================] - 0s 766us/step - loss: 0.0070 - val_loss: 0.0024
[2024-11-18T21:32:34.921+0000] {process_utils.py:190} INFO - Epoch 9/10
[2024-11-18T21:32:35.374+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0076 73/575 [==>...........................] - ETA: 0s - loss: 0.0072146/575 [======>.......................] - ETA: 0s - loss: 0.0072224/575 [==========>...................] - ETA: 0s - loss: 0.0071299/575 [==============>...............] - ETA: 0s - loss: 0.0070381/575 [==================>...........] - ETA: 0s - loss: 0.0069460/575 [=======================>......] - ETA: 0s - loss: 0.0069538/575 [===========================>..] - ETA: 0s - loss: 0.0069575/575 [==============================] - 0s 788us/step - loss: 0.0069 - val_loss: 0.0024
[2024-11-18T21:32:35.374+0000] {process_utils.py:190} INFO - Epoch 10/10
[2024-11-18T21:32:35.816+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0078 83/575 [===>..........................] - ETA: 0s - loss: 0.0067161/575 [=======>......................] - ETA: 0s - loss: 0.0067243/575 [===========>..................] - ETA: 0s - loss: 0.0067324/575 [===============>..............] - ETA: 0s - loss: 0.0067405/575 [====================>.........] - ETA: 0s - loss: 0.0067474/575 [=======================>......] - ETA: 0s - loss: 0.0066552/575 [===========================>..] - ETA: 0s - loss: 0.0066575/575 [==============================] - 0s 769us/step - loss: 0.0066 - val_loss: 0.0018
[2024-11-18T21:32:36.206+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 28s105/719 [===>..........................] - ETA: 0s 213/719 [=======>......................] - ETA: 0s323/719 [============>.................] - ETA: 0s437/719 [=================>............] - ETA: 0s541/719 [=====================>........] - ETA: 0s653/719 [==========================>...] - ETA: 0s719/719 [==============================] - 0s 459us/step
[2024-11-18T21:32:36.761+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 8s102/719 [===>..........................] - ETA: 0s204/719 [=======>......................] - ETA: 0s311/719 [===========>..................] - ETA: 0s423/719 [================>.............] - ETA: 0s531/719 [=====================>........] - ETA: 0s643/719 [=========================>....] - ETA: 0s719/719 [==============================] - 0s 469us/step
[2024-11-18T21:32:36.891+0000] {process_utils.py:190} INFO - 2024/11/18 21:32:36 WARNING mlflow.tensorflow: You are saving a TensorFlow Core model or Keras model without a signature. Inference with mlflow.pyfunc.spark_udf() will not work unless the model's pyfunc representation accepts pandas DataFrames as inference inputs.
[2024-11-18T21:32:37.231+0000] {process_utils.py:190} INFO - [[34m2024-11-18T21:32:37.231+0000[0m] {[34mbuilder_impl.py:[0m804} INFO[0m - Assets written to: /tmp/tmp7a2x8t8h/model/data/model/assets[0m
[2024-11-18T21:32:39.743+0000] {process_utils.py:190} INFO - /tmp/venvid5tekn7/lib/python3.8/site-packages/_distutils_hack/__init__.py:33 UserWarning: Setuptools is replacing distutils.
[2024-11-18T21:32:39.760+0000] {process_utils.py:190} INFO - [[34m2024-11-18T21:32:39.759+0000[0m] {[34mcredentials.py:[0m1124} INFO[0m - Found credentials in environment variables.[0m
[2024-11-18T21:32:39.879+0000] {process_utils.py:190} INFO - Registered model 'spotify_model_prod' already exists. Creating a new version of this model...
[2024-11-18T21:32:39.879+0000] {process_utils.py:190} INFO - 2024/11/18 21:32:39 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: spotify_model_prod, version 19
[2024-11-18T21:32:39.880+0000] {process_utils.py:190} INFO - Created version '19' of model 'spotify_model_prod'.
[2024-11-18T21:32:39.880+0000] {process_utils.py:190} INFO - /tmp/venvid5tekn7/lib/python3.8/site-packages/keras/src/engine/training.py:3000 UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
[2024-11-18T21:32:39.908+0000] {process_utils.py:190} INFO - Error saving data_info/song_embeddings.json to MinIO: [Errno 2] No such file or directory: 'data_info/song_embeddings.json'
[2024-11-18T21:32:40.851+0000] {python.py:201} INFO - Done. Returned value was: Challenger model trained and logged.
[2024-11-18T21:32:40.885+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=spotify_retrain_challenge_model_v3, task_id=train_challenger_model, execution_date=20241118T212648, start_date=20241118T213211, end_date=20241118T213240
[2024-11-18T21:32:40.902+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-11-18T21:32:40.913+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
