[2024-11-18T18:04:33.518+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_recommender_dag_v3.preprocess_and_split manual__2024-11-18T18:04:26.253565+00:00 [queued]>
[2024-11-18T18:04:33.522+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_recommender_dag_v3.preprocess_and_split manual__2024-11-18T18:04:26.253565+00:00 [queued]>
[2024-11-18T18:04:33.522+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-11-18T18:04:33.528+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): preprocess_and_split> on 2024-11-18 18:04:26.253565+00:00
[2024-11-18T18:04:33.531+0000] {standard_task_runner.py:60} INFO - Started process 3816 to run task
[2024-11-18T18:04:33.533+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_recommender_dag_v3', 'preprocess_and_split', 'manual__2024-11-18T18:04:26.253565+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/music_process.py', '--cfg-path', '/tmp/tmpcyzmowqm']
[2024-11-18T18:04:33.534+0000] {standard_task_runner.py:88} INFO - Job 65: Subtask preprocess_and_split
[2024-11-18T18:04:33.560+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_recommender_dag_v3.preprocess_and_split manual__2024-11-18T18:04:26.253565+00:00 [running]> on host 98017b53a184
[2024-11-18T18:04:34.216+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_recommender_dag_v3' AIRFLOW_CTX_TASK_ID='preprocess_and_split' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T18:04:26.253565+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T18:04:26.253565+00:00'
[2024-11-18T18:04:34.217+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venv9z_ts8gm --system-site-packages --python=python
[2024-11-18T18:04:34.221+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:04:34.549+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 117ms
[2024-11-18T18:04:34.549+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venv9z_ts8gm, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T18:04:34.550+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T18:04:34.551+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-11-18T18:04:34.551+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T18:04:34.567+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv9z_ts8gm/bin/pip install -r /tmp/venv9z_ts8gm/requirements.txt
[2024-11-18T18:04:34.571+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:04:35.506+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venv9z_ts8gm/requirements.txt (line 1))
[2024-11-18T18:04:35.508+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T18:04:35.508+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venv9z_ts8gm/requirements.txt (line 2)) (2.0.3)
[2024-11-18T18:04:35.509+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn==1.3.2 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venv9z_ts8gm/requirements.txt (line 3)) (1.3.2)
[2024-11-18T18:04:35.941+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venv9z_ts8gm/requirements.txt (line 1))
[2024-11-18T18:04:35.942+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T18:04:35.944+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venv9z_ts8gm/requirements.txt (line 1)) (0.10.0)
[2024-11-18T18:04:35.967+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venv9z_ts8gm/requirements.txt (line 1))
[2024-11-18T18:04:35.969+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:04:36.020+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venv9z_ts8gm/requirements.txt (line 2)) (2.8.2)
[2024-11-18T18:04:36.020+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venv9z_ts8gm/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T18:04:36.021+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venv9z_ts8gm/requirements.txt (line 2)) (2023.4)
[2024-11-18T18:04:36.021+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy>=1.20.3 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venv9z_ts8gm/requirements.txt (line 2)) (1.24.4)
[2024-11-18T18:04:36.041+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy>=1.5.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venv9z_ts8gm/requirements.txt (line 3)) (1.10.1)
[2024-11-18T18:04:36.041+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venv9z_ts8gm/requirements.txt (line 3)) (1.4.2)
[2024-11-18T18:04:36.041+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venv9z_ts8gm/requirements.txt (line 3)) (3.5.0)
[2024-11-18T18:04:36.046+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venv9z_ts8gm/requirements.txt (line 1)) (1.26.18)
[2024-11-18T18:04:36.050+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas==2.0.3->-r /tmp/venv9z_ts8gm/requirements.txt (line 2)) (1.16.0)
[2024-11-18T18:04:36.280+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T18:04:36.281+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T18:04:36.292+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T18:04:38.020+0000] {process_utils.py:190} INFO - Installing collected packages: botocore, s3transfer, boto3
[2024-11-18T18:04:38.020+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T18:04:38.021+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T18:04:38.021+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv9z_ts8gm
[2024-11-18T18:04:38.021+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T18:04:38.429+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T18:04:38.431+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T18:04:38.431+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv9z_ts8gm
[2024-11-18T18:04:38.432+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T18:04:38.452+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T18:04:38.452+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T18:04:38.453+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv9z_ts8gm
[2024-11-18T18:04:38.453+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T18:04:38.483+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T18:04:38.484+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T18:04:38.484+0000] {process_utils.py:190} INFO - Successfully installed boto3-1.28.0 botocore-1.31.85 s3transfer-0.6.2
[2024-11-18T18:04:38.556+0000] {process_utils.py:190} INFO - 
[2024-11-18T18:04:38.557+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.3.1
[2024-11-18T18:04:38.557+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T18:04:38.686+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv9z_ts8gm/bin/python /tmp/venv-callhjdsatwn/script.py /tmp/venv-callhjdsatwn/script.in /tmp/venv-callhjdsatwn/script.out /tmp/venv-callhjdsatwn/string_args.txt /tmp/venv-callhjdsatwn/termination.log
[2024-11-18T18:04:38.690+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:04:40.580+0000] {python.py:201} INFO - Done. Returned value was: Data preprocessed and saved.
[2024-11-18T18:04:40.598+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=spotify_recommender_dag_v3, task_id=preprocess_and_split, execution_date=20241118T180426, start_date=20241118T180433, end_date=20241118T180440
[2024-11-18T18:04:40.628+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-11-18T18:04:40.637+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
